// server/src/features/skills/seed/build.ts — the deterministic generator of skills.seed.json.
//
//   npx tsx server/src/features/skills/seed/build.ts            print what would change
//   npx tsx server/src/features/skills/seed/build.ts --write    write skills.seed.json
//
// Inputs, all in the repository (MATCH 4.6: seed from what we already know):
//   terms.ts                    the tables of features/match/terms.ts, which
//                               live in this area since MKT-2G: SHOWN_BY (named
//                               tool → broader term: the parent edges),
//                               displayTerm (the usual spelling),
//                               EVERYDAY_WORDS (the `everydayWord` flag)
//   features/search/skills.ts   SKILL_ALIASES (k8s → Kubernetes, js →
//                               JavaScript), through the copy in sources.ts
//                               that seed.test.ts holds in step
//   seed/sources.ts             ids and labels of the broader terms, which
//                               spellings are one tool, more tool names, soft
//                               skills, certificates
//   seed/reviewed.json          skills a reviewer approved in the database,
//                               written by `cli.ts export-seed`; an entry here
//                               replaces the generated one with the same id
//   seed/additions.json         what the table added to a seed skill without a
//                               review of the skill itself: learned alias keys
//                               and ESCO / O*NET identifiers. Applied on top of
//                               the generated entry, which stays generated
//   seed/dropped.json           what a reviewer dropped: ids of seed skills
//                               (left out of the seed) and keys of strings that
//                               are never a skill again ("fast-paced
//                               environment"). Both written by `export-seed`
//
// The same inputs give the same bytes. The seed test compares the committed
// file with this output, so a change to any input fails until the file is
// regenerated with --write.
//
// Every entry is `reviewed`, has no ESCO or O*NET identifier (those come only
// from `cli.ts attach-ids`), and no alias key leads to two ids (the build
// throws).

import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { displayTerm, isEverydayWord, SHOWN_BY } from '../terms.js';
import { aliasKey, slugOf } from '../keys.js';
import { SKILL_KINDS, type SkillKind, type SkillRecord } from '../types.js';
import additionsJson from './additions.json' with { type: 'json' };
import droppedJson from './dropped.json' with { type: 'json' };
import reviewedJson from './reviewed.json' with { type: 'json' };
import { CERTIFICATIONS, EXTRA_SKILLS, GENERAL_SKILLS, PARENT_CHOICE, SOFT_SKILLS, SPECIFIC_SKILLS, TYPEAHEAD_SKILL_ALIASES, type Curated } from './sources.js';

/** One entry of skills.seed.json: a reviewed SkillRecord. */
export type SeedSkill = SkillRecord & { status: 'reviewed' };

/** What the table added to a seed skill: alias keys and identifiers, nothing else (seed/additions.json). */
export interface SeedAddition {
  id: string;
  aliasKeys: string[];
  esco: string | null;
  onet: string | null;
}

/** What a reviewer dropped (seed/dropped.json). */
export interface SeedDropped {
  /** Seed skills that are no skill any more (dropped, or merged into another). */
  ids: string[];
  /** Comparison keys of strings that are never a skill again. */
  keys: string[];
}

export interface SeedFile {
  _about: string;
  version: 1;
  skills: SeedSkill[];
  /** Comparison keys that are never a skill: the keys of seed/dropped.json and every key of a dropped seed skill that no live skill holds. Sorted. */
  dropped: string[];
}

export const SEED_ABOUT =
  'Generated by server/src/features/skills/seed/build.ts from terms.ts, seed/sources.ts, seed/reviewed.json, seed/additions.json and seed/dropped.json. Do not edit by hand: change an input and run the generator with --write.';

interface Draft {
  id: string;
  kind: SkillKind;
  labelEn: string;
  labelZh: string | null;
  labelZhHant: string | null;
  /** Every name except the label, as written. */
  names: string[];
  parentId: string | null;
  /** Broader skills of the SHOWN_BY rows that list this tool. */
  generals: Set<string>;
}

function fail(message: string): never {
  throw new Error(`skills seed: ${message}`);
}

const strings = (v: unknown): string[] => (Array.isArray(v) ? v.filter((x): x is string => typeof x === 'string' && !!x) : []);

/** The reviewed overlay as records (a bad entry stops the build). */
export function parseReviewed(value: unknown): SeedSkill[] {
  if (!Array.isArray(value)) fail('reviewed.json must be an array');
  return (value as unknown[]).map((raw, i) => {
    const e = raw as Partial<SeedSkill>;
    if (!e || typeof e.id !== 'string' || !e.id || typeof e.labelEn !== 'string' || !e.labelEn) fail(`reviewed.json entry ${i} needs an id and a labelEn`);
    if (!(SKILL_KINDS as readonly string[]).includes(String(e.kind))) fail(`reviewed.json entry ${e.id} has an unknown kind`);
    const keys = strings(e.aliasKeys);
    return {
      id: e.id!,
      kind: e.kind as SkillKind,
      labelEn: e.labelEn!,
      labelZh: typeof e.labelZh === 'string' && e.labelZh ? e.labelZh : null,
      labelZhHant: typeof e.labelZhHant === 'string' && e.labelZhHant ? e.labelZhHant : null,
      aliases: strings(e.aliases),
      parentId: typeof e.parentId === 'string' && e.parentId ? e.parentId : null,
      esco: typeof e.esco === 'string' && e.esco ? e.esco : null,
      onet: typeof e.onet === 'string' && e.onet ? e.onet : null,
      status: 'reviewed',
      ...(keys.length ? { aliasKeys: keys } : {}),
      ...(e.everydayWord === true ? { everydayWord: true as const } : {}),
    };
  });
}

/** seed/additions.json as records (a bad entry stops the build). */
export function parseAdditions(value: unknown): SeedAddition[] {
  if (!Array.isArray(value)) fail('additions.json must be an array');
  return (value as unknown[]).map((raw, i) => {
    const e = raw as Partial<SeedAddition>;
    if (!e || typeof e.id !== 'string' || !e.id) fail(`additions.json entry ${i} needs an id`);
    return { id: e.id!, aliasKeys: strings(e.aliasKeys), esco: typeof e.esco === 'string' && e.esco ? e.esco : null, onet: typeof e.onet === 'string' && e.onet ? e.onet : null };
  });
}

/** seed/dropped.json as a record (a bad shape stops the build). */
export function parseDropped(value: unknown): SeedDropped {
  const e = value as Partial<SeedDropped> | null;
  if (!e || typeof e !== 'object' || Array.isArray(e)) fail('dropped.json must be an object with "ids" and "keys"');
  return { ids: strings(e!.ids), keys: strings(e!.keys) };
}

function sortStrings(values: Iterable<string>): string[] {
  return [...new Set(values)].sort((a, b) => (a < b ? -1 : a > b ? 1 : 0));
}

/** Every comparison key a record gives: its labels, its spellings, its stored keys and its own id. */
function keysOfRecord(r: SkillRecord): string[] {
  const keys = [r.labelEn, r.labelZh, r.labelZhHant, ...r.aliases, r.id.replace(/_/g, ' ')].filter((n): n is string => !!n).map(aliasKey);
  return [...keys, ...(r.aliasKeys ?? [])].filter(Boolean);
}

export interface BuildSeedOptions {
  reviewed?: readonly SeedSkill[];
  additions?: readonly SeedAddition[];
  dropped?: SeedDropped;
}

/** Build the seed. Each option defaults to its committed file (seed/reviewed.json, seed/additions.json, seed/dropped.json). */
export function buildSeed(options: BuildSeedOptions = {}): SeedFile {
  const reviewed = options.reviewed ?? parseReviewed(reviewedJson);
  const additions = options.additions ?? parseAdditions(additionsJson);
  const dropped = options.dropped ?? parseDropped(droppedJson);
  const drafts = new Map<string, Draft>();
  /** Comparison key → the draft that has it. */
  const owner = new Map<string, string>();

  const claim = (id: string, name: string): void => {
    const key = aliasKey(name);
    if (!key) fail(`"${name}" of ${id} has no comparison key`);
    const has = owner.get(key);
    if (has !== undefined && has !== id) fail(`"${name}" would lead to two skills: ${has} and ${id}`);
    owner.set(key, id);
  };

  const add = (c: Curated, generated: { id?: string; parent?: string | null } = {}): Draft => {
    const id = c.id ?? generated.id ?? slugOf(c.names[0]!);
    if (!/^[a-z0-9_]+$/.test(id)) fail(`"${id}" is not a plain id: give ${JSON.stringify(c.names[0])} an id in sources.ts`);
    if (drafts.has(id)) fail(`the id ${id} is used twice`);
    const labelEn = c.labelEn ?? displayTerm(c.names[0]!);
    const draft: Draft = {
      id,
      kind: c.kind ?? 'hard',
      labelEn,
      labelZh: c.labelZh ?? null,
      labelZhHant: c.labelZhHant ?? null,
      names: [...c.names, ...(c.aliases ?? [])],
      parentId: c.parent ?? generated.parent ?? null,
      generals: new Set(),
    };
    drafts.set(id, draft);
    for (const name of [labelEn, draft.labelZh, draft.labelZhHant, ...draft.names]) if (name) claim(id, name);
    return draft;
  };

  // 1. Named tools of SHOWN_BY: one skill per group of spellings.
  const groupOf = new Map<string, Curated>();
  for (const c of SPECIFIC_SKILLS) for (const name of c.names) groupOf.set(name, c);
  const draftOfGroup = new Map<Curated, Draft>();
  const generalIdOfRow: string[] = [];
  for (const [general] of SHOWN_BY) {
    const head = general[0]!;
    const cfg = GENERAL_SKILLS[head];
    if (!cfg) fail(`terms.ts SHOWN_BY has a row "${head}" with no entry in sources.ts GENERAL_SKILLS`);
    generalIdOfRow.push(cfg.id);
  }
  SHOWN_BY.forEach(([, specific], row) => {
    for (const name of specific) {
      const cfg = groupOf.get(name) ?? { names: [name] };
      let draft = draftOfGroup.get(cfg) ?? drafts.get(cfg.id ?? slugOf(cfg.names[0]!));
      if (!draft) draft = add(cfg);
      draftOfGroup.set(cfg, draft);
      draft.generals.add(generalIdOfRow[row]!);
    }
  });
  const unused = SPECIFIC_SKILLS.filter((c) => !draftOfGroup.has(c));
  if (unused.length) fail(`sources.ts SPECIFIC_SKILLS lists a tool SHOWN_BY no longer has: ${unused.map((c) => c.names[0]).join(', ')}`);

  // 2. The broader terms. A term a named tool already has stays with the tool ("rest apis").
  for (const [general] of SHOWN_BY) {
    const cfg = GENERAL_SKILLS[general[0]!]!;
    const own = cfg.own ?? {};
    const names = general.filter((g) => !(g in own) && owner.get(aliasKey(g)) === undefined);
    if (names[0] !== general[0]) fail(`the broader term "${general[0]}" is already the name of ${owner.get(aliasKey(general[0]!))}`);
    add({ ...cfg, names: [...names] });
    for (const [term, o] of Object.entries(own)) {
      if (!general.includes(term)) fail(`"${term}" is not a term of the row "${general[0]}"`);
      add({ id: o.id, names: [term], labelEn: o.labelEn });
    }
  }

  // 3. One parent per tool: the broader skill deepest in the chain, or the choice sources.ts states.
  const ancestors = (id: string): Set<string> => {
    const out = new Set<string>();
    for (let at = drafts.get(id)?.parentId ?? null; at && !out.has(at); at = drafts.get(at)?.parentId ?? null) out.add(at);
    return out;
  };
  for (const draft of draftOfGroup.values()) {
    const candidates = [...draft.generals];
    const deepest = candidates.find((c) => candidates.every((other) => other === c || ancestors(c).has(other)));
    const chosen = deepest ?? PARENT_CHOICE[draft.id];
    if (!chosen || !draft.generals.has(chosen)) fail(`${draft.id} is listed under ${candidates.join(' and ')}: state its one parent in sources.ts PARENT_CHOICE`);
    draft.parentId = chosen;
  }

  // 4. More tool names, soft skills, certificates.
  for (const c of [...EXTRA_SKILLS, ...SOFT_SKILLS, ...CERTIFICATIONS]) add(c);

  // 5. The typeahead's alias table (features/search/skills.ts SKILL_ALIASES, through its copy in sources.ts).
  for (const [alias, target] of Object.entries(TYPEAHEAD_SKILL_ALIASES)) {
    const id = owner.get(aliasKey(target));
    if (!id) fail(`SKILL_ALIASES maps "${alias}" to "${target}", which is no seed skill: add it to sources.ts EXTRA_SKILLS`);
    claim(id, alias);
    drafts.get(id)!.names.push(alias);
  }

  // 6. Records.
  const records = new Map<string, SeedSkill>();
  for (const d of drafts.values()) {
    const labelKeys = new Set([d.labelEn, d.labelZh, d.labelZhHant].filter((l): l is string => !!l).map(aliasKey));
    const seen = new Set<string>();
    const aliases: string[] = [];
    for (const name of d.names) {
      const key = aliasKey(name);
      if (labelKeys.has(key) || seen.has(key)) continue;
      seen.add(key);
      aliases.push(name);
    }
    records.set(d.id, {
      id: d.id,
      kind: d.kind,
      labelEn: d.labelEn,
      labelZh: d.labelZh,
      labelZhHant: d.labelZhHant,
      aliases: sortStrings(aliases),
      parentId: d.parentId,
      esco: null,
      onet: null,
      status: 'reviewed',
      ...(isEverydayWord(d.labelEn) ? { everydayWord: true as const } : {}),
    });
  }

  // 7. What a reviewer approved replaces the generated entry of the same id.
  for (const r of reviewed) {
    const generated = records.get(r.id);
    records.set(r.id, {
      ...r,
      aliases: sortStrings(r.aliases),
      ...(r.aliasKeys?.length ? { aliasKeys: sortStrings(r.aliasKeys) } : {}),
      ...(r.everydayWord || generated?.everydayWord ? { everydayWord: true as const } : {}),
    });
  }

  // 8. What the table added to a seed skill: keys and identifiers on top of the entry, which stays as generated.
  for (const a of additions) {
    const r = records.get(a.id);
    if (!r) fail(`additions.json names ${a.id}, which is no seed skill: remove the entry`);
    const keys = sortStrings([...(r!.aliasKeys ?? []), ...a.aliasKeys]);
    records.set(a.id, { ...r!, ...(keys.length ? { aliasKeys: keys } : {}), esco: r!.esco ?? a.esco, onet: r!.onet ?? a.onet });
  }

  // 9. What a reviewer dropped: the seed skill is left out and its names are never a skill again.
  //    A skill under it loses its parent, as it does where the row was dropped (a parent that is no skill is ignored).
  const droppedKeys = new Set(dropped.keys);
  const gone = new Set<string>();
  for (const id of dropped.ids) {
    const r = records.get(id);
    if (!r) continue;
    for (const key of keysOfRecord(r)) droppedKeys.add(key);
    records.delete(id);
    gone.add(id);
  }
  if (gone.size) for (const r of records.values()) if (r.parentId && gone.has(r.parentId)) records.set(r.id, { ...r, parentId: null });

  // 10. One key, one id; every parent exists.
  const keyOwner = new Map<string, string>();
  /** `quiet`: a skill's own id is a convenience name; losing it to another skill's label is not an error. */
  const take = (id: string, key: string, what: string, quiet = false): void => {
    if (!key) return;
    const has = keyOwner.get(key);
    if (has !== undefined && has !== id) {
      if (quiet) return;
      fail(`${what} leads to two skills: ${has} and ${id}`);
    }
    keyOwner.set(key, id);
  };
  for (const r of records.values()) {
    for (const name of [r.labelEn, r.labelZh, r.labelZhHant, ...r.aliases]) if (name) take(r.id, aliasKey(name), `"${name}"`);
    for (const key of r.aliasKeys ?? []) take(r.id, key, `the key "${key}"`);
    if (r.parentId && !records.has(r.parentId)) fail(`${r.id} has the parent ${r.parentId}, which is no seed skill`);
    if (r.parentId === r.id) fail(`${r.id} is its own parent`);
  }
  // A skill's own id is a name of it too, when no other skill has that name (vocabulary.ts does the same).
  for (const r of records.values()) take(r.id, aliasKey(r.id.replace(/_/g, ' ')), `the id "${r.id}"`, true);

  const skills = [...records.values()].sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
  // A key a live skill holds is that skill's name, not a dropped string.
  return { _about: SEED_ABOUT, version: 1, skills, dropped: sortStrings([...droppedKeys].filter((key) => key && !keyOwner.has(key))) };
}

function entryOf(s: SeedSkill): Record<string, unknown> {
  return {
    id: s.id,
    kind: s.kind,
    labelEn: s.labelEn,
    labelZh: s.labelZh,
    labelZhHant: s.labelZhHant,
    aliases: s.aliases,
    ...(s.aliasKeys?.length ? { aliasKeys: s.aliasKeys } : {}),
    parentId: s.parentId,
    esco: s.esco,
    onet: s.onet,
    status: s.status,
    ...(s.everydayWord ? { everydayWord: true } : {}),
  };
}

/** The exact bytes of skills.seed.json. */
export function serializeSeed(file: SeedFile): string {
  return `${JSON.stringify({ _about: file._about, version: file.version, skills: file.skills.map(entryOf), dropped: file.dropped }, null, 2)}\n`;
}

/** The exact bytes of additions.json: the entries sorted by id, their keys sorted. */
export function serializeAdditions(additions: readonly SeedAddition[]): string {
  const sorted = [...additions].sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
  return `${JSON.stringify(sorted.map((a) => ({ id: a.id, aliasKeys: sortStrings(a.aliasKeys), esco: a.esco, onet: a.onet })), null, 2)}\n`;
}

/** The exact bytes of dropped.json: ids and keys sorted. */
export function serializeDropped(dropped: SeedDropped): string {
  return `${JSON.stringify({ ids: sortStrings(dropped.ids), keys: sortStrings(dropped.keys) }, null, 2)}\n`;
}

/** The exact bytes of reviewed.json: the entries sorted by id. */
export function serializeReviewed(reviewed: readonly SeedSkill[]): string {
  const sorted = [...reviewed].sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
  return `${JSON.stringify(sorted.map(entryOf), null, 2)}\n`;
}

export const SEED_PATH = path.join(path.dirname(fileURLToPath(import.meta.url)), 'skills.seed.json');
export const REVIEWED_PATH = path.join(path.dirname(fileURLToPath(import.meta.url)), 'reviewed.json');
export const ADDITIONS_PATH = path.join(path.dirname(fileURLToPath(import.meta.url)), 'additions.json');
export const DROPPED_PATH = path.join(path.dirname(fileURLToPath(import.meta.url)), 'dropped.json');

async function main(): Promise<void> {
  const fs = await import('node:fs');
  const write = process.argv.includes('--write');
  const next = serializeSeed(buildSeed());
  const have = fs.existsSync(SEED_PATH) ? fs.readFileSync(SEED_PATH, 'utf8') : '';
  const count = (JSON.parse(next) as SeedFile).skills.length;
  if (have === next) {
    // eslint-disable-next-line no-console
    console.log(`skills.seed.json is up to date (${count} skills).`);
    return;
  }
  if (!write) {
    // eslint-disable-next-line no-console
    console.log(`skills.seed.json differs from the generator's output (${count} skills). Run again with --write to write it.`);
    process.exitCode = 1;
    return;
  }
  fs.writeFileSync(SEED_PATH, next);
  // eslint-disable-next-line no-console
  console.log(`Wrote skills.seed.json (${count} skills).`);
}

// Run only as a script, never when imported.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch((err) => {
    // eslint-disable-next-line no-console
    console.error(err instanceof Error ? err.message : err);
    process.exit(1);
  });
}
