// server/src/features/retrieval/buildHantHans.ts
//
// Generates the Traditional → Simplified character table of `hantHans.ts` from
// the Unicode Unihan database. Run by hand, never at build time:
//
//   npx tsx server/src/features/retrieval/buildHantHans.ts <path>/Unihan_Variants.txt            # print the block
//   npx tsx server/src/features/retrieval/buildHantHans.ts <path>/Unihan_Variants.txt --write    # rewrite hantHans.ts
//
// Source: `Unihan_Variants.txt` inside https://www.unicode.org/Public/UCD/latest/ucd/Unihan.zip
// (Unicode licence; the file's own header names its version and date, which is
// copied into the generated block). Lines are `U+XXXX<tab>kSimplifiedVariant<tab>U+YYYY [U+ZZZZ …]`.
//
// Rule: a character maps to the first of its simplified variants that is not
// the character itself. A character with no such variant is left out. One
// Traditional character becomes one Simplified character; the table is for
// search tokens, where 乾 → 干 is the wanted fold even though 乾 also exists in
// Simplified text.
//
// After the table changes, every live posting must be indexed again
// (`retrieval/cli.ts backfill --all --apply`): the stored tokens come from the old table.

import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

export interface HantHansBuild {
  /** e.g. '17.0.0'; null when the file's header names none. */
  unicodeVersion: string | null;
  table: Record<string, string>;
}

const START = '// <generated:hant-hans>';
const END = '// </generated:hant-hans>';

function charOf(codePoint: string): string | null {
  const m = /^U\+([0-9A-F]{4,6})/i.exec(codePoint.trim());
  if (!m) return null;
  const n = Number.parseInt(m[1]!, 16);
  return Number.isFinite(n) && n > 0 && n <= 0x10ffff ? String.fromCodePoint(n) : null;
}

/** Parse the text of Unihan_Variants.txt. Pure: no file access. */
export function parseUnihanVariants(text: string): HantHansBuild {
  const version = /Unicode(?:\s+Character\s+Database)?[^\n]*?(\d+\.\d+\.\d+)/i.exec(text.slice(0, 4000))?.[1] ?? /Unihan_Variants-(\d+\.\d+\.\d+)/.exec(text.slice(0, 4000))?.[1] ?? null;
  const entries: Array<[string, string]> = [];
  for (const line of text.split(/\r?\n/)) {
    if (!line || line.startsWith('#')) continue;
    const [cp, field, value] = line.split('\t');
    if (field !== 'kSimplifiedVariant' || !cp || !value) continue;
    const from = charOf(cp);
    if (!from) continue;
    const to = value
      .split(/\s+/)
      .map((v) => charOf(v))
      .find((c): c is string => !!c && c !== from);
    if (to) entries.push([from, to]);
  }
  entries.sort((a, b) => a[0].codePointAt(0)! - b[0].codePointAt(0)!);
  return { unicodeVersion: version, table: Object.fromEntries(entries) };
}

/** The generated block of hantHans.ts for a build. */
export function renderHantHansBlock(build: HantHansBuild): string {
  const pairs = Object.entries(build.table);
  const rows: string[] = [];
  for (let i = 0; i < pairs.length; i += 12) {
    rows.push(`  ${pairs.slice(i, i + 12).map(([k, v]) => `${JSON.stringify(k)}: ${JSON.stringify(v)},`).join(' ')}`);
  }
  return [
    START,
    `// Generated by buildHantHans.ts from Unihan_Variants.txt (kSimplifiedVariant), Unicode ${build.unicodeVersion ?? 'version not stated in the file'}: ${pairs.length} characters. Do not edit by hand.`,
    '/** The Unicode version of the Unihan file the table was generated from; null while the table is empty. */',
    `export const HANT_HANS_UNICODE_VERSION: string | null = ${JSON.stringify(build.unicodeVersion)};`,
    '/** Traditional character → Simplified character (Unihan kSimplifiedVariant). Empty until generated. */',
    pairs.length ? `export const HANT_HANS: Readonly<Record<string, string>> = {\n${rows.join('\n')}\n};` : 'export const HANT_HANS: Readonly<Record<string, string>> = {};',
    END,
  ].join('\n');
}

/** Replace the generated block in the source of hantHans.ts. Throws when the markers are missing. */
export function replaceHantHansBlock(source: string, block: string): string {
  const start = source.indexOf(START);
  const end = source.indexOf(END);
  if (start < 0 || end < start) throw new Error('hantHans.ts: the generated-block markers are missing');
  return source.slice(0, start) + block + source.slice(end + END.length);
}

function main(argv: string[]): void {
  const file = argv.find((a) => !a.startsWith('--'));
  if (!file) {
    console.error('usage: tsx server/src/features/retrieval/buildHantHans.ts <path>/Unihan_Variants.txt [--write]');
    process.exitCode = 1;
    return;
  }
  const build = parseUnihanVariants(readFileSync(file, 'utf8'));
  const count = Object.keys(build.table).length;
  if (count < 1000) {
    console.error(`Only ${count} kSimplifiedVariant entries found in ${file}: this does not look like Unihan_Variants.txt. Nothing written.`);
    process.exitCode = 1;
    return;
  }
  const block = renderHantHansBlock(build);
  if (!argv.includes('--write')) {
    console.log(block);
    return;
  }
  const target = path.join(path.dirname(fileURLToPath(import.meta.url)), 'hantHans.ts');
  writeFileSync(target, replaceHantHansBlock(readFileSync(target, 'utf8'), block));
  console.log(`hantHans.ts: ${count} characters from Unicode ${build.unicodeVersion ?? '(version not stated)'}. Now re-index: retrieval/cli.ts backfill --all --apply.`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main(process.argv.slice(2));
