// @vitest-environment node
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { parseUnihanVariants, renderHantHansBlock, replaceHantHansBlock } from './buildHantHans.js';
import { HANT_HANS, HANT_HANS_UNICODE_VERSION, foldHantToHans, isTraditionalOnly } from './hantHans.js';

const here = path.dirname(fileURLToPath(import.meta.url));

describe('Traditional → Simplified fold (search copy only)', () => {
  it('folds Taiwan vocabulary first, then characters', () => {
    expect(foldHantToHans('軟體工程師')).toBe('软件工程师');
    expect(foldHantToHans('資料分析師')).toBe('数据分析师');
    expect(foldHantToHans('產品經理')).toBe('产品经理');
  });

  it('leaves Simplified text, Latin text and kana as they are', () => {
    expect(foldHantToHans('产品经理')).toBe('产品经理');
    expect(foldHantToHans('Senior Engineer')).toBe('Senior Engineer');
    expect(foldHantToHans('エンジニア')).toBe('エンジニア');
  });

  it('calls a character Traditional-only exactly when the fold changes it', () => {
    expect(isTraditionalOnly('產')).toBe(true);
    expect(isTraditionalOnly('产')).toBe(false);
    expect(isTraditionalOnly('人')).toBe(false);
    expect(isTraditionalOnly('a')).toBe(false);
  });

  it('states where its table comes from: generated from Unihan with the Unicode version, or empty and said so', () => {
    const source = readFileSync(path.join(here, 'hantHans.ts'), 'utf8');
    const size = Object.keys(HANT_HANS).length;
    if (size === 0) {
      // Not generated yet: no version is claimed and the file says how to fill it.
      expect(HANT_HANS_UNICODE_VERSION).toBeNull();
      expect(source).toContain('STATE OF THE TABLE: it is EMPTY');
      expect(source).toContain('Unihan_Variants.txt');
    } else {
      expect(HANT_HANS_UNICODE_VERSION).toMatch(/^\d+\.\d+\.\d+$/);
      expect(size).toBeGreaterThan(1000);
      expect(source).toContain('Generated by buildHantHans.ts from Unihan_Variants.txt');
    }
  });
});

describe('buildHantHans (the generator; SYNTHETIC sample of the file format)', () => {
  // SYNTHETIC: four lines in the layout of Unihan_Variants.txt, written for this test.
  const sample = [
    '# Unihan_Variants.txt',
    '# Unicode Character Database, version 17.0.0',
    'U+7522\tkSimplifiedVariant\tU+4EA7',
    'U+7D93\tkSimplifiedVariant\tU+7ECF',
    'U+4E7E\tkSimplifiedVariant\tU+4E7E U+5E72',
    'U+7522\tkTraditionalVariant\tU+7522',
    'U+4EBA\tkSemanticVariant\tU+4EBB',
    'U+8457\tkSimplifiedVariant\tU+8457',
    '',
  ].join('\n');

  it('reads kSimplifiedVariant only, takes the first variant that is not the character itself, and reads the version', () => {
    const build = parseUnihanVariants(sample);
    expect(build.unicodeVersion).toBe('17.0.0');
    expect(build.table).toEqual({ 乾: '干', 產: '产', 經: '经' });
  });

  it('renders a block the module can hold and replaces only that block', () => {
    const block = renderHantHansBlock(parseUnihanVariants(sample));
    expect(block).toContain('export const HANT_HANS_UNICODE_VERSION: string | null = "17.0.0";');
    expect(block).toContain('"產": "产",');
    const source = readFileSync(path.join(here, 'hantHans.ts'), 'utf8');
    const next = replaceHantHansBlock(source, block);
    expect(next).toContain('"經": "经",');
    expect(next).toContain('export function foldHantToHans');
    expect(next.split('// <generated:hant-hans>')).toHaveLength(2);
    expect(() => replaceHantHansBlock('no markers here', block)).toThrow(/markers/);
    // An empty build renders the empty table the module ships with.
    expect(renderHantHansBlock({ unicodeVersion: null, table: {} })).toContain('export const HANT_HANS: Readonly<Record<string, string>> = {};');
  });
});
