// server/src/features/retrieval/hantHans.ts
//
// Traditional → Simplified folding for the SEARCH COPY of a text only
// (MARKET_STRATEGY 2.5 row "Lexical tokens"; SM-11). A zh-TW posting and a
// zh-CN query (or the reverse) must produce the same tokens, so both sides are
// folded to Simplified before they are segmented. The folded text is stored in
// `RAJob.searchDoc` and never displayed (zh-TW must never show Simplified text).
//
// Two layers, applied in this order:
//   1. the Taiwan vocabulary of `jobs/normalize` `foldTwToCn` (軟體 → 软件,
//      資料 → 数据, …) with its own character list;
//   2. `HANT_HANS`, a character table generated by `buildHantHans.ts` from the
//      Unicode Unihan database (`Unihan_Variants.txt`, field kSimplifiedVariant).
//
// STATE OF THE TABLE: it is EMPTY. The Unihan file could not be obtained when
// this module was written (MKT-2H: no file download was allowed in that
// session), and a table of thousands of characters is never typed from memory.
// Until someone runs the generator, layer 1 alone folds: the roughly 130
// characters and 23 terms of job-title vocabulary in `zhVariants.ts`. To fill it:
//
//   1. download https://www.unicode.org/Public/UCD/latest/ucd/Unihan.zip and unpack Unihan_Variants.txt
//   2. npx tsx server/src/features/retrieval/buildHantHans.ts <path>/Unihan_Variants.txt --write
//   3. re-index every live posting, because documents indexed with the old
//      table hold other tokens than a query folded with the new one:
//      npx tsx server/src/features/retrieval/cli.ts backfill --market intl --all --apply (and --market cn)
//
// The generator rewrites the block between the two markers below and nothing else.

import { foldTwToCn } from '../jobs/normalize/index.js';

// <generated:hant-hans>
/** The Unicode version of the Unihan file the table was generated from; null while the table is empty. */
export const HANT_HANS_UNICODE_VERSION: string | null = null;
/** Traditional character → Simplified character (Unihan kSimplifiedVariant). Empty until generated. */
export const HANT_HANS: Readonly<Record<string, string>> = {};
// </generated:hant-hans>

const HAN = /\p{Script=Han}/u;
const traditionalOnly = new Map<string, boolean>();

/** Fold Taiwan vocabulary and Traditional characters to Simplified ones. For search tokens only; never shown. */
export function foldHantToHans(text: string): string {
  if (!HAN.test(text)) return text;
  const folded = foldTwToCn(text);
  let out = '';
  for (const ch of folded) out += Object.prototype.hasOwnProperty.call(HANT_HANS, ch) ? HANT_HANS[ch]! : ch;
  return out;
}

/**
 * True for a character only Traditional text uses: the fold changes it. This
 * is "a key of the fold table" over both layers, so language detection and
 * folding can never disagree about which characters are Traditional.
 */
export function isTraditionalOnly(ch: string): boolean {
  let known = traditionalOnly.get(ch);
  if (known === undefined) {
    known = HAN.test(ch) && foldHantToHans(ch) !== ch;
    // Language detection asks about every Han character of a posting: remember the answers (a few thousand characters at most).
    if (traditionalOnly.size < 20_000) traditionalOnly.set(ch, known);
  }
  return known;
}
