// lib/mockInterview/fixtures.ts
//
// 25 system-built mock interviews across 11 categories. Each is a focused
// 15-minute drill anchored around 6 questions — long enough to feel real,
// short enough that a user actually finishes. Difficulty is set so the
// landing grid has visual variety (mostly Medium with a few Easy and Hard).
//
// Gradients are paired with the category palette so the grid reads at a
// glance. Picking the gradient is deterministic so the snapshot test stays
// stable.

import type { MockInterview } from './types';

const G = {
  mint:   { from: '#cffafe', to: '#a7f3d0' },
  sky:    { from: '#dbeafe', to: '#c7d2fe' },
  violet: { from: '#ede9fe', to: '#fbcfe8' },
  rose:   { from: '#fee2e2', to: '#fbcfe8' },
  amber:  { from: '#fef3c7', to: '#fef9c3' },
  emerald:{ from: '#d1fae5', to: '#a7f3d0' },
  peach:  { from: '#ffe4e6', to: '#fde68a' },
  lilac:  { from: '#e9d5ff', to: '#fbcfe8' },
  ice:    { from: '#dbeafe', to: '#e0f2fe' },
  lemon:  { from: '#fef9c3', to: '#fef08a' },
  forest: { from: '#dcfce7', to: '#bbf7d0' },
} as const;

export const FIXTURE_MOCKS: MockInterview[] = [
  // ── IT ────────────────────────────────────────────────────────────
  {
    id: 'mk_it_redis',
    title: 'Redis Deep Dive',
    description: 'Walk through Redis data types, persistence trade-offs, and how you tune it for hot paths.',
    category: 'it',
    duration: 15,
    difficulty: 'medium',
    gradient: G.violet,
    skills: ['Redis', 'caching', 'memory', 'persistence'],
    questions: [
      {
        id: 'q1', kind: 'technical',
        prompt: 'Walk me through every Redis data type you have used in production. Where did each one shine and where did it bite?',
        expectedKeywords: ['string', 'hash', 'list', 'set', 'sorted set', 'stream', 'hyperloglog'],
        sampleAnswer: 'Strings for caches, Hashes for object-like records, Sorted Sets for leaderboards (O(log N) range), Streams for fan-out where Kafka was overkill, and HyperLogLog for cheap unique counts.',
      },
      { id: 'q2', kind: 'technical',
        prompt: 'Your Redis hit rate just dropped from 95% to 70%. Walk me through your diagnosis in real time.',
        expectedKeywords: ['hit rate', 'eviction', 'memory', 'INFO', 'SLOWLOG', 'monitor'],
        followUp: 'How would you reproduce this in a staging environment to confirm your hypothesis?',
      },
      { id: 'q3', kind: 'technical',
        prompt: 'RDB vs AOF — when would you pick each, and what surprises have you hit running both?',
        expectedKeywords: ['RDB', 'AOF', 'fsync', 'snapshot', 'durability'],
      },
      { id: 'q4', kind: 'technical',
        prompt: 'Walk me through Redis Cluster slot resharding. What goes wrong if a client lags during a slot move?',
        expectedKeywords: ['cluster', 'slot', 'MOVED', 'ASK', 'resharding'],
      },
      { id: 'q5', kind: 'technical',
        prompt: 'Design a rate limiter for a public API on Redis. 100 requests per user per minute.',
        expectedKeywords: ['token bucket', 'sliding window', 'INCR', 'EXPIRE', 'lua'],
        sampleAnswer: 'Sliding window with Lua atomic: ZADD a timestamp, ZREMRANGEBYSCORE expired entries, ZCARD vs limit, all in one Lua script so it is atomic.',
      },
      { id: 'q6', kind: 'behavioral',
        prompt: 'Tell me about a time a Redis outage was your fault. What did you change after?',
      },
    ],
  },
  {
    id: 'mk_it_network',
    title: 'Network Engineer',
    description: 'Maintain and optimise the network — designing reliable, secure, scalable infrastructure.',
    category: 'it',
    duration: 15,
    difficulty: 'medium',
    gradient: G.mint,
    skills: ['TCP/IP', 'BGP', 'firewall', 'load balancing'],
    questions: [
      { id: 'q1', kind: 'technical', prompt: 'Walk me through what happens, layer by layer, when a user hits your domain from their phone.', expectedKeywords: ['dns', 'tcp', 'tls', 'http', 'load balancer'] },
      { id: 'q2', kind: 'technical', prompt: 'Your customers in APAC are seeing 800ms tail latency to a US origin. Walk me through your triage.', expectedKeywords: ['cdn', 'edge', 'tcp', 'mtu', 'traceroute'] },
      { id: 'q3', kind: 'technical', prompt: 'Explain BGP convergence in your own words. Why does the internet still go down occasionally?', expectedKeywords: ['bgp', 'as', 'route', 'convergence'] },
      { id: 'q4', kind: 'technical', prompt: 'Pick a load balancer (L4 vs L7) and defend the choice for a payments API.', expectedKeywords: ['L4', 'L7', 'tls', 'sticky'] },
      { id: 'q5', kind: 'technical', prompt: 'You suspect a noisy-neighbor issue in your VPC. How do you prove it?', expectedKeywords: ['vpc', 'flow logs', 'noisy', 'tenancy'] },
      { id: 'q6', kind: 'behavioral', prompt: 'Describe your worst on-call incident. What did the post-mortem move you to change?' },
    ],
  },
  {
    id: 'mk_it_sql_injection',
    title: 'SQL Injection',
    description: 'Identify, prevent, and remediate SQL injection vulnerabilities across the stack.',
    category: 'it',
    duration: 15,
    difficulty: 'medium',
    gradient: G.emerald,
    skills: ['SQL', 'security', 'OWASP', 'parameterized queries'],
    questions: [
      { id: 'q1', kind: 'technical', prompt: 'Explain SQL injection in two sentences without using any code.', expectedKeywords: ['user input', 'query', 'attacker'] },
      { id: 'q2', kind: 'technical', prompt: 'Walk me through three different classes of SQL injection and how they are detected.', expectedKeywords: ['error-based', 'blind', 'union', 'time'], followUp: 'Which of these is the hardest to spot in production traffic?' },
      { id: 'q3', kind: 'technical', prompt: 'I have a Rails app already deployed. What is the order of operations you take to harden it against SQLi this week?', expectedKeywords: ['parameterized', 'ORM', 'audit', 'WAF'] },
      { id: 'q4', kind: 'technical', prompt: 'When does an ORM still leave you exposed to SQLi?', expectedKeywords: ['raw', 'interpolation', 'order by'] },
      { id: 'q5', kind: 'technical', prompt: 'Design a CI step that catches SQLi regressions before merge.', expectedKeywords: ['static', 'sast', 'snyk', 'review'] },
      { id: 'q6', kind: 'behavioral', prompt: 'Tell me about a security finding you escalated against the wishes of the team. How did it land?' },
    ],
  },
  {
    id: 'mk_it_blockchain',
    title: 'Blockchain Application Engineer',
    description: 'Build smart contracts and dApps end-to-end. Solidity, audit posture, gas optimisation.',
    category: 'it',
    duration: 15,
    difficulty: 'hard',
    gradient: G.sky,
    skills: ['Solidity', 'EVM', 'gas', 'smart contracts'],
    questions: [
      { id: 'q1', kind: 'technical', prompt: 'Walk me through the EVM gas model. Where do most people overpay?', expectedKeywords: ['gas', 'opcode', 'storage', 'memory', 'calldata'] },
      { id: 'q2', kind: 'technical', prompt: 'Design an upgradeable contract that you actually trust in production.', expectedKeywords: ['proxy', 'delegatecall', 'storage slot', 'admin'] },
      { id: 'q3', kind: 'technical', prompt: 'Re-entrancy: explain it, and walk me through three defenses.', expectedKeywords: ['re-entrancy', 'checks-effects-interactions', 'mutex', 'pull pattern'] },
      { id: 'q4', kind: 'technical', prompt: 'You have a contract that has been audited but you suspect a bug. Walk me through your live response.', expectedKeywords: ['pause', 'multisig', 'fork', 'mev'] },
      { id: 'q5', kind: 'technical', prompt: 'Pick a layer-2 and defend your choice for a 100k-DAU consumer app.', expectedKeywords: ['l2', 'rollup', 'optimistic', 'zk', 'fee'] },
      { id: 'q6', kind: 'behavioral', prompt: 'Tell me about a security trade-off you made that you would defend in front of an auditor.' },
    ],
  },
  {
    id: 'mk_it_rb_tree',
    title: 'Red-Black Tree',
    description: 'Explain the invariants, walk through rotations, and reason about real-world use.',
    category: 'it',
    duration: 15,
    difficulty: 'hard',
    gradient: G.amber,
    skills: ['data structures', 'algorithms', 'self-balancing'],
    questions: [
      { id: 'q1', kind: 'technical', prompt: 'State the five red-black tree invariants without looking them up.', expectedKeywords: ['root', 'black', 'red', 'leaf', 'path'] },
      { id: 'q2', kind: 'technical', prompt: 'Walk me through inserting a node that causes a double-red. Show the recoloring + rotation choice.', expectedKeywords: ['recolor', 'left rotation', 'right rotation', 'uncle'] },
      { id: 'q3', kind: 'technical', prompt: 'Why O(log N) — what is the actual bound on the height?', expectedKeywords: ['height', 'log', '2 log'] },
      { id: 'q4', kind: 'technical', prompt: 'Pick between Red-Black and AVL for a write-heavy in-memory index. Defend the call.', expectedKeywords: ['avl', 'rotations', 'balance', 'write'] },
      { id: 'q5', kind: 'technical', prompt: 'Where have you seen red-black trees inside real systems?', expectedKeywords: ['linux', 'cfs', 'epoll', 'java treemap'] },
      { id: 'q6', kind: 'behavioral', prompt: 'Tell me about a time you picked a clever data structure that turned out to be the wrong call.' },
    ],
  },
  {
    id: 'mk_it_mvc',
    title: 'MVC Pattern',
    description: 'Explain the contract between Model, View, and Controller across a real framework.',
    category: 'it',
    duration: 15,
    difficulty: 'easy',
    gradient: G.peach,
    skills: ['MVC', 'separation of concerns', 'architecture'],
    questions: [
      { id: 'q1', kind: 'technical', prompt: 'Define MVC in one sentence per component.', expectedKeywords: ['model', 'view', 'controller'] },
      { id: 'q2', kind: 'technical', prompt: 'Walk me through a request through a Vue 3 + a Node controller from URL to DB and back.', expectedKeywords: ['router', 'controller', 'service', 'model', 'response'] },
      { id: 'q3', kind: 'technical', prompt: 'Where does business logic live in your MVC apps — and where should it not?', expectedKeywords: ['service', 'thin controller', 'fat model'] },
      { id: 'q4', kind: 'technical', prompt: 'Critique MVC for a real-time collaborative editor.', expectedKeywords: ['state', 'sync', 'crdt', 'reactive'] },
      { id: 'q5', kind: 'technical', prompt: 'How is MVVM different from MVC? When would you reach for it?', expectedKeywords: ['mvvm', 'binding', 'view model'] },
      { id: 'q6', kind: 'behavioral', prompt: 'Walk me through a refactor where you moved logic out of a controller.' },
    ],
  },
  {
    id: 'mk_it_threads',
    title: 'Threads & Coroutines',
    description: 'Reason about concurrency models — OS threads, green threads, async/await, coroutines.',
    category: 'it',
    duration: 15,
    difficulty: 'medium',
    gradient: G.ice,
    skills: ['concurrency', 'async', 'threads'],
    questions: [
      { id: 'q1', kind: 'technical', prompt: 'Threads vs coroutines in Python — describe the moment each one wins.', expectedKeywords: ['gil', 'asyncio', 'thread', 'coroutine'] },
      { id: 'q2', kind: 'technical', prompt: 'Explain the GIL like I am new to Python.', expectedKeywords: ['gil', 'lock', 'cpu-bound', 'io-bound'] },
      { id: 'q3', kind: 'technical', prompt: 'What is a deadlock and how do you detect one in a running service?', expectedKeywords: ['deadlock', 'cycle', 'lock order', 'thread dump'] },
      { id: 'q4', kind: 'technical', prompt: 'Pick between threadpool + blocking I/O and a fully async stack for a payments microservice.', expectedKeywords: ['blocking', 'async', 'throughput', 'latency'] },
      { id: 'q5', kind: 'technical', prompt: 'Walk me through structured concurrency in your own words.', expectedKeywords: ['scope', 'cancel', 'lifetime', 'children'] },
      { id: 'q6', kind: 'behavioral', prompt: 'Tell me about a race condition that bit you in prod.' },
    ],
  },
  {
    id: 'mk_it_aop_ioc',
    title: 'AOP & IoC',
    description: 'Aspect-Oriented Programming and Inversion of Control in Spring — concepts and trade-offs.',
    category: 'it',
    duration: 15,
    difficulty: 'medium',
    gradient: G.lilac,
    skills: ['Spring', 'AOP', 'IoC', 'DI'],
    questions: [
      { id: 'q1', kind: 'technical', prompt: 'Explain IoC and DI as if to a junior engineer.', expectedKeywords: ['ioc', 'dependency', 'inject', 'control'] },
      { id: 'q2', kind: 'technical', prompt: 'Walk me through the Spring container lifecycle.', expectedKeywords: ['bean', 'lifecycle', 'context', 'singleton'] },
      { id: 'q3', kind: 'technical', prompt: 'Where would you use AOP in a real-world product?', expectedKeywords: ['logging', 'audit', 'transactional', 'pointcut'] },
      { id: 'q4', kind: 'technical', prompt: 'Critique AOP. Where have you seen it cause more pain than it solved?', expectedKeywords: ['debug', 'magic', 'observability'] },
      { id: 'q5', kind: 'technical', prompt: 'Compare Spring AOP with AspectJ.', expectedKeywords: ['proxy', 'weave', 'compile', 'load-time'] },
      { id: 'q6', kind: 'behavioral', prompt: 'When have you chosen explicitness over a framework convention?' },
    ],
  },
  {
    id: 'mk_it_frontend',
    title: 'Frontend Engineer',
    description: 'Build delightful, performant UIs. State, performance, accessibility, design partnership.',
    category: 'it',
    duration: 15,
    difficulty: 'medium',
    gradient: G.rose,
    skills: ['React', 'performance', 'accessibility', 'state'],
    questions: [
      { id: 'q1', kind: 'technical', prompt: 'A page is janky on scroll. Walk me through your performance investigation.', expectedKeywords: ['paint', 'reflow', 'devtools', 'frame', 'layer'] },
      { id: 'q2', kind: 'technical', prompt: 'State management in a 200-screen app — what is your default and when do you reach for something else?', expectedKeywords: ['context', 'redux', 'zustand', 'query', 'state'] },
      { id: 'q3', kind: 'technical', prompt: 'How do you ship an accessible date picker?', expectedKeywords: ['aria', 'keyboard', 'screen reader', 'focus'] },
      { id: 'q4', kind: 'technical', prompt: 'Server components vs client components — when do you reach for each?', expectedKeywords: ['rsc', 'client', 'bundle', 'data'] },
      { id: 'q5', kind: 'technical', prompt: 'Walk me through your bundle-size strategy on a real product.', expectedKeywords: ['code split', 'lazy', 'tree shake', 'analyze'] },
      { id: 'q6', kind: 'behavioral', prompt: 'Tell me about a design partnership where you and the designer disagreed. How did it resolve?' },
    ],
  },
  {
    id: 'mk_it_cloud',
    title: 'Cloud Specialist',
    description: 'Cloud architecture, cost, resilience. AWS / GCP / Azure interchangeable — pick yours.',
    category: 'it',
    duration: 15,
    difficulty: 'medium',
    gradient: G.lemon,
    skills: ['AWS', 'cloud', 'cost', 'resilience'],
    questions: [
      { id: 'q1', kind: 'system_design', prompt: 'Design a multi-region active-active backend for a payments API.', expectedKeywords: ['region', 'replication', 'consistency', 'rds', 'dynamodb'] },
      { id: 'q2', kind: 'technical', prompt: 'Your cloud bill jumped 40% with no traffic change. Walk me through your investigation.', expectedKeywords: ['cost explorer', 'tag', 'egress', 'idle'] },
      { id: 'q3', kind: 'technical', prompt: 'How do you choose between serverless and a container platform?', expectedKeywords: ['lambda', 'fargate', 'kubernetes', 'cold start'] },
      { id: 'q4', kind: 'technical', prompt: 'Describe your default observability stack on AWS.', expectedKeywords: ['cloudwatch', 'xray', 'metric', 'log'] },
      { id: 'q5', kind: 'technical', prompt: 'How do you sleep through a region failure?', expectedKeywords: ['multi-region', 'failover', 'rpo', 'rto'] },
      { id: 'q6', kind: 'behavioral', prompt: 'Tell me about a cloud migration that did NOT go to plan.' },
    ],
  },
  {
    id: 'mk_it_dba',
    title: 'Database Administrator',
    description: 'Design, deploy and maintain databases — performance, durability, recovery.',
    category: 'it',
    duration: 15,
    difficulty: 'medium',
    gradient: G.mint,
    skills: ['SQL', 'replication', 'backups', 'performance'],
    questions: [
      { id: 'q1', kind: 'technical', prompt: 'Walk me through how Postgres handles a long-running transaction.', expectedKeywords: ['mvcc', 'snapshot', 'vacuum', 'bloat'] },
      { id: 'q2', kind: 'technical', prompt: 'A query that was 50ms yesterday is 5s today. Triage live.', expectedKeywords: ['explain', 'analyze', 'index', 'stats', 'lock'] },
      { id: 'q3', kind: 'technical', prompt: 'Backups vs PITR — what is the right answer for a fintech startup?', expectedKeywords: ['backup', 'pitr', 'rpo', 'wal'] },
      { id: 'q4', kind: 'technical', prompt: 'When would you reach for a non-relational database?', expectedKeywords: ['nosql', 'document', 'key-value', 'graph', 'scale'] },
      { id: 'q5', kind: 'technical', prompt: 'Talk me through your zero-downtime schema migration playbook.', expectedKeywords: ['migration', 'expand', 'contract', 'backfill'] },
      { id: 'q6', kind: 'behavioral', prompt: 'Tell me about a data-loss incident you contained.' },
    ],
  },
  {
    id: 'mk_it_mobile',
    title: 'Mobile Engineer',
    description: 'Build native + cross-platform apps. Performance, offline, app store ops.',
    category: 'it',
    duration: 15,
    difficulty: 'medium',
    gradient: G.peach,
    skills: ['iOS', 'Android', 'React Native', 'offline'],
    questions: [
      { id: 'q1', kind: 'technical', prompt: 'Native vs cross-platform — make a call for a banking app and defend it.', expectedKeywords: ['native', 'react native', 'flutter', 'platform'] },
      { id: 'q2', kind: 'technical', prompt: 'How do you build an offline-first mobile experience?', expectedKeywords: ['offline', 'sync', 'queue', 'sqlite', 'crdt'] },
      { id: 'q3', kind: 'technical', prompt: 'Walk me through your mobile release process.', expectedKeywords: ['testflight', 'staged rollout', 'crash', 'rollback'] },
      { id: 'q4', kind: 'technical', prompt: 'A user reports the app hangs on launch on Android 9. Triage.', expectedKeywords: ['profile', 'startup', 'systrace', 'logcat'] },
      { id: 'q5', kind: 'technical', prompt: 'How do you keep an app under 50MB?', expectedKeywords: ['app bundle', 'asset', 'split', 'optimize'] },
      { id: 'q6', kind: 'behavioral', prompt: 'Tell me about an app store rejection. How did you turn it around?' },
    ],
  },
  {
    id: 'mk_it_backend',
    title: 'Backend Engineer',
    description: 'Server + database + API design. Reliability, observability, scale.',
    category: 'it',
    duration: 15,
    difficulty: 'medium',
    gradient: G.violet,
    skills: ['APIs', 'databases', 'distributed systems'],
    questions: [
      { id: 'q1', kind: 'system_design', prompt: 'Design the backend for a viral photo-sharing app.', expectedKeywords: ['upload', 's3', 'cdn', 'cache', 'feed', 'fan-out'] },
      { id: 'q2', kind: 'technical', prompt: 'Idempotency keys — what are they and where do they save your bacon?', expectedKeywords: ['idempotency', 'retry', 'unique', 'side effect'] },
      { id: 'q3', kind: 'technical', prompt: 'A queue is backing up. Walk me through diagnosis.', expectedKeywords: ['queue', 'consumer', 'lag', 'partition', 'throughput'] },
      { id: 'q4', kind: 'technical', prompt: 'Pick a default SQL vs NoSQL — defend it.', expectedKeywords: ['postgres', 'dynamodb', 'consistency', 'scale'] },
      { id: 'q5', kind: 'technical', prompt: 'How do you avoid the N+1 problem and how do you catch it in CI?', expectedKeywords: ['n+1', 'eager', 'preload', 'query log'] },
      { id: 'q6', kind: 'behavioral', prompt: 'Tell me about a feature you over-engineered. What would you do differently?' },
    ],
  },
  {
    id: 'mk_it_fullstack',
    title: 'Full-Stack Engineer',
    description: 'Both ends and the bits in between. Web + backend + ops at small-team scale.',
    category: 'it',
    duration: 15,
    difficulty: 'medium',
    gradient: G.sky,
    skills: ['React', 'Node', 'Postgres', 'ops'],
    questions: [
      { id: 'q1', kind: 'technical', prompt: 'You are employee #4 at a startup. Sketch the stack you would default to.', expectedKeywords: ['react', 'next', 'postgres', 'vercel', 'render'] },
      { id: 'q2', kind: 'technical', prompt: 'What is the smallest deploy pipeline you would still trust?', expectedKeywords: ['ci', 'cd', 'preview', 'rollback'] },
      { id: 'q3', kind: 'technical', prompt: 'Walk me through how you implement auth at week 1 vs year 3.', expectedKeywords: ['auth', 'session', 'jwt', 'oauth', 'rbac'] },
      { id: 'q4', kind: 'technical', prompt: 'You own everything. How do you sleep at night?', expectedKeywords: ['alerting', 'sentry', 'metrics', 'on-call'] },
      { id: 'q5', kind: 'technical', prompt: 'Design a feature flag system from scratch in 5 minutes.', expectedKeywords: ['flag', 'rollout', 'cache', 'sdk'] },
      { id: 'q6', kind: 'behavioral', prompt: 'Tell me about a decision you reversed. What did you learn?' },
    ],
  },

  // ── Data ──────────────────────────────────────────────────────────
  {
    id: 'mk_data_analyst',
    title: 'Data Analyst',
    description: 'Turn messy data into a decision. SQL fluency, framing, stakeholder management.',
    category: 'data',
    duration: 15,
    difficulty: 'easy',
    gradient: G.emerald,
    skills: ['SQL', 'dashboards', 'communication'],
    questions: [
      { id: 'q1', kind: 'technical', prompt: 'Walk me through a window-function query you have actually shipped.', expectedKeywords: ['over', 'partition', 'row_number', 'rank'] },
      { id: 'q2', kind: 'case', prompt: 'Weekly active users dropped 8%. You have one hour. What do you do?', expectedKeywords: ['hypothesis', 'segment', 'cohort', 'funnel'] },
      { id: 'q3', kind: 'technical', prompt: 'When do you NOT use a median?', expectedKeywords: ['skew', 'outlier', 'distribution', 'mean'] },
      { id: 'q4', kind: 'behavioral', prompt: 'Tell me about a dashboard you killed.' },
      { id: 'q5', kind: 'case', prompt: 'A stakeholder wants a 100-row breakdown, you want a single chart. Walk me through the conversation.' },
      { id: 'q6', kind: 'technical', prompt: 'Walk through how you set up A/B tests for someone non-technical.', expectedKeywords: ['hypothesis', 'sample size', 'significance', 'p-value'] },
    ],
  },

  // ── AI ────────────────────────────────────────────────────────────
  {
    id: 'mk_ai_engineer',
    title: 'AI / ML Engineer',
    description: 'Train + deploy + monitor. Prompts, evals, fine-tuning, latency, cost.',
    category: 'ai',
    duration: 15,
    difficulty: 'hard',
    gradient: G.lilac,
    skills: ['LLMs', 'evals', 'fine-tuning', 'RAG'],
    questions: [
      { id: 'q1', kind: 'technical', prompt: 'Design an eval harness for an LLM feature you have shipped.', expectedKeywords: ['eval', 'golden set', 'rubric', 'regression'] },
      { id: 'q2', kind: 'technical', prompt: 'Prompt engineering vs fine-tuning vs RAG — when does each win?', expectedKeywords: ['prompt', 'fine-tune', 'rag', 'cost', 'latency'] },
      { id: 'q3', kind: 'technical', prompt: 'Your model is hallucinating in production. Walk me through your response.', expectedKeywords: ['grounding', 'citation', 'retrieval', 'guardrail'] },
      { id: 'q4', kind: 'system_design', prompt: 'Design a customer support bot for a B2B SaaS company.', expectedKeywords: ['rag', 'tool use', 'eval', 'escalation', 'handoff'] },
      { id: 'q5', kind: 'technical', prompt: 'How do you keep a $X model bill from running away?', expectedKeywords: ['caching', 'routing', 'small model', 'batch'] },
      { id: 'q6', kind: 'behavioral', prompt: 'Tell me about a time you cut an ML feature because it was not adding value.' },
    ],
  },

  // ── Product ───────────────────────────────────────────────────────
  {
    id: 'mk_pm_senior',
    title: 'Senior Product Manager',
    description: 'Strategy, prioritisation, execution, and stakeholder dance. Real PM behaviorals.',
    category: 'product',
    duration: 15,
    difficulty: 'medium',
    gradient: G.peach,
    skills: ['prioritisation', 'strategy', 'execution', 'data'],
    questions: [
      { id: 'q1', kind: 'behavioral', prompt: 'Walk me through a recent prioritisation call. Name the trade-off you made.', followUp: 'What would have to be true for the deprioritised work to win the next quarter?' },
      { id: 'q2', kind: 'case', prompt: 'Our key metric is flat for three quarters. What is your first week?' },
      { id: 'q3', kind: 'case', prompt: 'Design the next 18 months for Spotify Wrapped.' },
      { id: 'q4', kind: 'behavioral', prompt: 'Tell me about a disagreement with an engineer that you lost. What changed in you?' },
      { id: 'q5', kind: 'case', prompt: 'Pick a B2C app you love and three weaknesses. Now pick the one you would kill first.' },
      { id: 'q6', kind: 'behavioral', prompt: 'Tell me about a product you killed.' },
    ],
  },

  // ── Business ──────────────────────────────────────────────────────
  {
    id: 'mk_biz_consultant',
    title: 'Strategy Consultant',
    description: 'Structured thinking under time pressure. Case fluency + executive presence.',
    category: 'business',
    duration: 15,
    difficulty: 'hard',
    gradient: G.amber,
    skills: ['case interview', 'structure', 'estimation'],
    questions: [
      { id: 'q1', kind: 'case', prompt: 'How many flights take off from JFK in a day?' },
      { id: 'q2', kind: 'case', prompt: 'A coffee chain is losing share to a new entrant. Walk me through your framework.' },
      { id: 'q3', kind: 'case', prompt: 'An airline asks you whether to merge with a budget carrier. Five-minute answer.' },
      { id: 'q4', kind: 'behavioral', prompt: 'Tell me about a time you led a partner who was 20 years more senior than you.' },
      { id: 'q5', kind: 'case', prompt: 'Pick an industry and tell me the most under-priced lever in it right now.' },
      { id: 'q6', kind: 'behavioral', prompt: 'A client asks for a recommendation that you disagree with. What do you do?' },
    ],
  },

  // ── Project Mgmt ─────────────────────────────────────────────────
  {
    id: 'mk_pjm_lead',
    title: 'Project Manager',
    description: 'Run programs across teams. Scope, risk, comms, deadlines.',
    category: 'project',
    duration: 15,
    difficulty: 'medium',
    gradient: G.ice,
    skills: ['risk', 'comms', 'planning'],
    questions: [
      { id: 'q1', kind: 'behavioral', prompt: 'Tell me about a project you delivered late. What did you do differently next time?' },
      { id: 'q2', kind: 'case', prompt: 'You inherit a project at 80% complete and three weeks of deadline. What is your first week?' },
      { id: 'q3', kind: 'behavioral', prompt: 'Walk me through a stakeholder you had to manage who was actively hostile.' },
      { id: 'q4', kind: 'case', prompt: 'Build a critical path for shipping a new payments product in 90 days.' },
      { id: 'q5', kind: 'behavioral', prompt: 'When have you cut scope under pressure?' },
      { id: 'q6', kind: 'behavioral', prompt: 'Tell me about the riskiest dependency you owned.' },
    ],
  },

  // ── Media ─────────────────────────────────────────────────────────
  {
    id: 'mk_media_host',
    title: 'Livestream Host / Content Creator',
    description: 'On-camera presence, audience growth, monetisation, brand partnerships.',
    category: 'media',
    duration: 15,
    difficulty: 'medium',
    gradient: G.rose,
    skills: ['on-camera', 'audience growth', 'brand'],
    questions: [
      { id: 'q1', kind: 'roleplay', prompt: 'Open your livestream right now. Three minutes. Go.' },
      { id: 'q2', kind: 'case', prompt: 'Your watch time has plateaued at 100k. Walk me through your growth thesis.' },
      { id: 'q3', kind: 'behavioral', prompt: 'A sponsor asks for an integration you do not believe in. How do you handle it?' },
      { id: 'q4', kind: 'case', prompt: 'Pick a content niche and tell me how you would launch it from zero in 30 days.' },
      { id: 'q5', kind: 'behavioral', prompt: 'Tell me about a piece of content you over-prepared and it still flopped. Why?' },
      { id: 'q6', kind: 'roleplay', prompt: 'Pitch yourself to a brand sponsor. 60 seconds.' },
    ],
  },

  // ── Design ────────────────────────────────────────────────────────
  {
    id: 'mk_design_product',
    title: 'Product Designer',
    description: 'End-to-end product design. Research → ship → measure.',
    category: 'design',
    duration: 15,
    difficulty: 'medium',
    gradient: G.lilac,
    skills: ['research', 'IA', 'visual', 'systems'],
    questions: [
      { id: 'q1', kind: 'case', prompt: 'Walk me through a recent project — research, decisions, ship, measure.' },
      { id: 'q2', kind: 'case', prompt: 'Critique any onboarding flow you have used in the last week.' },
      { id: 'q3', kind: 'behavioral', prompt: 'Tell me about feedback you got from research that you wanted to push back on.' },
      { id: 'q4', kind: 'case', prompt: 'Design a calendar app for someone with ADHD. Two minutes.' },
      { id: 'q5', kind: 'behavioral', prompt: 'When have you killed your favorite design?' },
      { id: 'q6', kind: 'case', prompt: 'Pick an enterprise tool you use and redesign the worst surface in it.' },
    ],
  },

  // ── Marketing ─────────────────────────────────────────────────────
  {
    id: 'mk_mkt_growth',
    title: 'Growth Marketer',
    description: 'Acquisition, activation, retention. Channels, experiments, attribution.',
    category: 'marketing',
    duration: 15,
    difficulty: 'medium',
    gradient: G.peach,
    skills: ['acquisition', 'retention', 'attribution'],
    questions: [
      { id: 'q1', kind: 'case', prompt: 'A B2B SaaS at $2M ARR wants to triple in 18 months. Where do you start?' },
      { id: 'q2', kind: 'technical', prompt: 'Walk me through an attribution model you actually trust.', expectedKeywords: ['attribution', 'multi-touch', 'incrementality', 'mmm'] },
      { id: 'q3', kind: 'behavioral', prompt: 'Tell me about a campaign that flopped and what you took from it.' },
      { id: 'q4', kind: 'case', prompt: 'Design a 30-day experiment to lift activation by 20%.' },
      { id: 'q5', kind: 'behavioral', prompt: 'When have you fought against a brand decision the founder loved?' },
      { id: 'q6', kind: 'case', prompt: 'Your CAC just doubled. Triage.' },
    ],
  },

  // ── Finance ───────────────────────────────────────────────────────
  {
    id: 'mk_fin_analyst',
    title: 'Financial Analyst',
    description: 'Modeling, valuation, stakeholder communication.',
    category: 'finance',
    duration: 15,
    difficulty: 'medium',
    gradient: G.lemon,
    skills: ['modeling', 'valuation', 'communication'],
    questions: [
      { id: 'q1', kind: 'technical', prompt: 'Walk me through a DCF for a SaaS business you actually understand.', expectedKeywords: ['fcf', 'wacc', 'terminal', 'growth'] },
      { id: 'q2', kind: 'case', prompt: 'You are asked to recommend buy/hold/sell on a stock with one hour. Walk me through your day.' },
      { id: 'q3', kind: 'technical', prompt: 'When does a comparables-based valuation lie to you?', expectedKeywords: ['comps', 'multiple', 'growth', 'liquidity'] },
      { id: 'q4', kind: 'behavioral', prompt: 'Tell me about a model you found a serious bug in. How did it land?' },
      { id: 'q5', kind: 'case', prompt: 'Your CFO wants three-statement projections for the board in 48 hours. Plan.' },
      { id: 'q6', kind: 'behavioral', prompt: 'Walk me through a financial decision you helped reverse.' },
    ],
  },

  // ── Other ─────────────────────────────────────────────────────────
  {
    id: 'mk_other_leadership',
    title: 'First-Time Manager',
    description: 'Leading without authority. Hiring, feedback, conflict, growth.',
    category: 'other',
    duration: 15,
    difficulty: 'medium',
    gradient: G.forest,
    skills: ['leadership', 'feedback', 'hiring'],
    questions: [
      { id: 'q1', kind: 'behavioral', prompt: 'Walk me through how you gave hard feedback for the first time.' },
      { id: 'q2', kind: 'behavioral', prompt: 'Tell me about a hire that did not work out.' },
      { id: 'q3', kind: 'case', prompt: 'You inherit a team that is underperforming. What is your first 30 days?' },
      { id: 'q4', kind: 'behavioral', prompt: 'When have you advocated for someone in the room they were not in?' },
      { id: 'q5', kind: 'behavioral', prompt: 'Tell me about a conflict between two reports and how you handled it.' },
      { id: 'q6', kind: 'behavioral', prompt: 'What is the most useful piece of management advice you have not yet been able to apply?' },
    ],
  },
];
