// i18n/staging/index.ts — GENERATED by scripts/i18n-merge-staging.mjs. Do not edit;
// run `npm run i18n:merge -- --index` after adding a staging file.
//
// Every web staging namespace (`<ns>.en.json`), deep-merged. lib/i18n.ts merges
// STAGING_EN over en.json before deriving the other locales, so a staged key
// renders in English everywhere until INT translates it (ARCHITECTURE.md §10.1.2).
// Extension namespaces (extension, extension-cn) merge into the extension package.

import accountV2 from './accountV2.en.json';
import admin from './admin.en.json';
import applications from './applications.en.json';
import assistant from './assistant.en.json';
import auth from './auth.en.json';
import authCn from './authCn.en.json';
import billingCn from './billingCn.en.json';
import brand from './brand.en.json';
import campus from './campus.en.json';
import coaching from './coaching.en.json';
import competitiveness from './competitiveness.en.json';
import coverLetter from './coverLetter.en.json';
import credits from './credits.en.json';
import extensionWeb from './extensionWeb.en.json';
import filters from './filters.en.json';
import fit from './fit.en.json';
import growth from './growth.en.json';
import inbox from './inbox.en.json';
import invite from './invite.en.json';
import jobDetail from './jobDetail.en.json';
import jobImport from './jobImport.en.json';
import jobs from './jobs.en.json';
import jobsCn from './jobsCn.en.json';
import jobsTw from './jobsTw.en.json';
import landing from './landing.en.json';
import legal from './legal.en.json';
import nav from './nav.en.json';
import notifyCn from './notifyCn.en.json';
import offers from './offers.en.json';
import onboarding from './onboarding.en.json';
import onboardingCn from './onboardingCn.en.json';
import people from './people.en.json';
import practice from './practice.en.json';
import practiceCn from './practiceCn.en.json';
import practiceQuestions from './practiceQuestions.en.json';
import profile from './profile.en.json';
import pwa from './pwa.en.json';
import ready from './ready.en.json';
import resume from './resume.en.json';
import resumeBuilder from './resumeBuilder.en.json';
import resumeCheck from './resumeCheck.en.json';
import seo from './seo.en.json';
import tailor from './tailor.en.json';
import taxonomy from './taxonomy.en.json';
import tools from './tools.en.json';
import visitor from './visitor.en.json';

type Messages = { [key: string]: string | Messages };

function deepMerge(dst: Messages, src: Messages): Messages {
  for (const [k, v] of Object.entries(src)) {
    const prev = dst[k];
    if (v && typeof v === 'object' && prev && typeof prev === 'object') deepMerge(prev, v);
    else dst[k] = v && typeof v === 'object' ? deepMerge({}, v) : v;
  }
  return dst;
}

/** Staging namespaces, in file order. */
export const STAGING_NAMESPACES: readonly string[] = ['accountV2', 'admin', 'applications', 'assistant', 'auth', 'authCn', 'billingCn', 'brand', 'campus', 'coaching', 'competitiveness', 'coverLetter', 'credits', 'extensionWeb', 'filters', 'fit', 'growth', 'inbox', 'invite', 'jobDetail', 'jobImport', 'jobs', 'jobsCn', 'jobsTw', 'landing', 'legal', 'nav', 'notifyCn', 'offers', 'onboarding', 'onboardingCn', 'people', 'practice', 'practiceCn', 'practiceQuestions', 'profile', 'pwa', 'ready', 'resume', 'resumeBuilder', 'resumeCheck', 'seo', 'tailor', 'taxonomy', 'tools', 'visitor'];

/** All staged English strings (cloned, so callers may not mutate the JSON modules). */
export const STAGING_EN: Messages = [
  accountV2,
  admin,
  applications,
  assistant,
  auth,
  authCn,
  billingCn,
  brand,
  campus,
  coaching,
  competitiveness,
  coverLetter,
  credits,
  extensionWeb,
  filters,
  fit,
  growth,
  inbox,
  invite,
  jobDetail,
  jobImport,
  jobs,
  jobsCn,
  jobsTw,
  landing,
  legal,
  nav,
  notifyCn,
  offers,
  onboarding,
  onboardingCn,
  people,
  practice,
  practiceCn,
  practiceQuestions,
  profile,
  pwa,
  ready,
  resume,
  resumeBuilder,
  resumeCheck,
  seo,
  tailor,
  taxonomy,
  tools,
  visitor,
].reduce<Messages>((acc, bundle) => deepMerge(acc, JSON.parse(JSON.stringify(bundle)) as Messages), {});
