// backend/src/interview-engine/catalog/domainExperts.ts
//
// DOMAIN EXPERTS — the third orthogonal directive dimension of the Interview
// Engine, layered beside archetypes (HOW the interviewer probes,
// interviewArchetypes.ts) and formats (the STRUCTURE of the exercise,
// interviewFormats.ts). A domain expert carries the SUBSTANCE of a field:
// what a real law / finance / hardware / AI interviewer actually asks, how a
// credible insider sounds, and how the field separates authentic experience
// from fluent vocabulary. Authored by an 18-expert panel run (2026-07-10).
//
// Three directives per domain thread into three different stages, exactly like
// archetypes do:
//   voiceDirective      → composeVoiceSystemPrompt (the LIVE interviewer's field credibility)
//   blueprintDirective  → InterviewBlueprintAgent (domain-authentic question design)
//   evaluationLens      → the eval agents (appended to the archetype lens for grading)
//
// Resolution: an explicit key wins; otherwise classifyDomain() scores the role
// title (strong signal) and JD text (weak signal) against each domain's
// matchTerms. Below-threshold roles get NO domain lens — identical to the
// pre-domain-layer behavior, so generic roles never receive a wrong lens.
// The resolved domain is persisted inside the session's blueprint JSON
// (interviewPromptService) so evaluation grades through the same lens.

export type InterviewDomain =
  | 'software'
  | 'ai-ml'
  | 'data'
  | 'hardware'
  | 'product'
  | 'design'
  | 'marketing'
  | 'media'
  | 'sales'
  | 'finance'
  | 'accounting'
  | 'legal'
  | 'insurance'
  | 'healthcare'
  | 'consumer'
  | 'operations'
  | 'hr'
  | 'education';

export const INTERVIEW_DOMAINS: readonly InterviewDomain[] = [
  'software',
  'ai-ml',
  'data',
  'hardware',
  'product',
  'design',
  'marketing',
  'media',
  'sales',
  'finance',
  'accounting',
  'legal',
  'insurance',
  'healthcare',
  'consumer',
  'operations',
  'hr',
  'education',
];

export interface DomainExpertPlaybook {
  key: InterviewDomain;
  /** Stable English label (also shown in the master brief / preview). */
  labelEn: string;
  /** One-line description of what this expert lens tests. */
  summary: string;
  /** Lowercase role-title/JD keywords for the deterministic classifier. */
  matchTerms: string[];
  /** Injected into the question-design (blueprint) agent — domain SUBSTANCE. */
  blueprintDirective: string;
  /** Injected into the live voice interviewer system prompt — field credibility. */
  voiceDirective: string;
  /** Appended to the archetype evaluationLens — domain-authenticity grading. */
  evaluationLens: string;
  /** Sub-areas worth probing; threads into the blueprint brief. */
  deepDiveTopics: string[];
}

export const DOMAIN_EXPERTS: Record<InterviewDomain, DomainExpertPlaybook> = {
  'software': {
    key: 'software',
    labelEn: "Software Engineering",
    summary: "Tests whether a candidate can reason about real systems they built and operated — architecture trade-offs, production failures, and operational ownership — rather than reciting fluent framework vocabulary.",
    matchTerms: ["android developer", "application security", "backend", "ci/cd", "code review", "devops", "distributed systems", "engineering manager", "frontend", "full stack", "graphql", "incident response", "infrastructure as code", "ios developer", "kubernetes", "microservices", "node.js", "observability", "on-call", "platform engineer", "pull request", "react", "site reliability engineer", "software developer", "software engineer", "sre", "system design", "tech lead", "terraform", "typescript"],
    blueprintDirective: "Anchor questions in systems the candidate actually built and operated, not textbook designs. The exercise shapes that separate strong from weak in software are a system-design prompt scoped to their claimed scale, a production-incident walkthrough, a debugging scenario with an evolving symptom, and an architecture-decision autopsy. Strong candidates reveal themselves through trade-off reasoning under real constraints, failure-mode anticipation, and operational ownership; weak ones through framework name-dropping. Use stems like \"Walk me through the worst production incident you owned end to end,\" \"Design the notification pipeline you'd need at 50M users — start with the write path,\" \"Your p99 doubled after a deploy; what do you look at in the first ten minutes,\" \"Tell me about a migration you led and what you did with the long tail,\" and \"Where did you draw the wrong service boundary, and how did you find out.\" Fold in 2025-2026 realities: how they verify AI-generated code, platform-engineering golden paths, OpenTelemetry-grade observability, cloud cost trade-offs, supply-chain security. idealSignal is named systems, real QPS/latency/error-budget numbers, and the specific thing that broke; probeIfWeak demands the exact mechanism — the consistency model chosen, the query plan, the rollback that saved them.",
    voiceDirective: "Speak the way engineers speak in design reviews: p99 and p50, blast radius, idempotency, backpressure, feature flags, error budgets, hot paths — used naturally, never as decoration. When a candidate says \"we scaled it,\" immediately ask for the number; when they say \"we,\" ask what they personally wrote or decided; when they name a tool, ask what it was doing at 3 a.m. when it failed. If they misuse a term — conflating concurrency with parallelism, calling eventual consistency \"async\" — don't lecture; ask them to explain how it behaved in their system and let the gap surface itself. Two standing instincts: always ask how a design gets tested, deployed, and rolled back, and always ask what they'd do differently now.",
    evaluationLens: "Domain-authentic strength in software looks like trade-off reasoning bound to real constraints — a consistency model chosen for a stated reason, a rollout plan with a rollback path, latency and traffic numbers that cohere — plus evidence of operational ownership: on-call scars, post-mortems, monitoring added after being burned. Fluent-but-hollow answers name architectures and tools without ever descending below the framework layer, present designs with no testing, deployment, or failure story, or credit AI coding assistants with no account of how output was verified. Red flags: zero personal failure stories, \"we\" with no recoverable \"I,\" core terminology misused under gentle probing, every incident blamed on adjacent teams. Frame growth feedback the way a design review or promo packet would: name the missing evidence of scope, mechanism, and operational judgment.",
    deepDiveTopics: ["Distributed systems & scaling", "API & data modeling", "Frontend architecture & UI performance", "Mobile app architecture", "CI/CD & infrastructure as code", "Incident response & observability", "Security engineering practices", "Debugging & code quality", "Engineering leadership & delivery"],
  },
  'ai-ml': {
    key: 'ai-ml',
    labelEn: "AI & Machine Learning",
    summary: "Tests whether a candidate has genuinely built, evaluated, and operated ML and LLM systems in production — architecture trade-offs, eval rigor, and serving economics — rather than reciting model vocabulary.",
    matchTerms: ["ai agents", "applied scientist", "computer vision", "deep learning", "embeddings", "fine-tuning", "foundation models", "genai", "generative ai", "hugging face", "inference optimization", "langchain", "large language models", "llm", "llmops", "machine learning engineer", "ml engineer", "mlops", "model evaluation", "model serving", "nlp", "prompt engineering", "pytorch", "rag", "research engineer", "retrieval augmented generation", "rlhf", "sagemaker", "tensorflow", "vector database"],
    blueprintDirective: "Anchor every question in a system the candidate actually shipped, and design around the decisions that define this field: why fine-tune versus RAG versus prompt-plus-tools, how the eval existed before the demo did, and what the model cost to serve. The canonical exercises are the shipped-model post-mortem, the eval-design challenge, and the architecture defense — stems like \"Walk me through a model whose offline metrics didn't survive production,\" \"Why RAG here instead of fine-tuning, and what did retrieval quality cost you,\" \"Design an eval for an LLM feature with no ground truth,\" \"Where could leakage have crept into that training set,\" and \"What was your cost per request at p95 latency, and how did you cut it.\" Strong candidates separate on eval rigor, failure-mode awareness (hallucination, drift, prompt injection), and cost consciousness; weak ones recite architectures. Make idealSignal include named stacks (vLLM, LoRA, pgvector), real metrics with baselines, dataset sizes, and GPU budgets; make probeIfWeak demand the specific eval set, the ablation that justified the choice, and the incident where the model failed a real user.",
    voiceDirective: "Speak like someone who has debugged a training run at two in the morning: use precision-recall trade-offs, held-out sets, p95 latency, context windows, token costs, and eval harnesses naturally, and never say \"the AI\" when you mean the model. When a candidate quotes a metric, your reflex is to ask what the baseline was and what data the eval ran on; when they say \"we fine-tuned,\" ask what the training data looked like and why prompting or RAG lost the bake-off. If someone calls few-shot prompting fine-tuning or conflates validation with test data, restate it correctly in passing and watch whether they self-correct. Always chase the gap between offline numbers and what production actually did.",
    evaluationLens: "On top of the archetype lens, judge whether the candidate reasons like someone who owns models in production: strong answers justify architecture choices by constraints — latency, cost per token, data availability — describe evals built before launch with named baselines, and volunteer failure modes like leakage, drift, hallucination, and offline-online metric gaps. Fluent-but-hollow answers name-drop transformers and agents but cannot say what the eval set contained or what a request cost to serve. Red-flag anything that treats benchmark scores as production evidence, claims fine-tuning that was really prompting, or has no monitoring story. Frame growth feedback in the field's terms: build the eval harness first, quantify serving economics, and instrument for drift before the next launch.",
    deepDiveTopics: ["RAG vs fine-tuning trade-offs", "eval design & LLM-as-judge", "classic ML fundamentals & leakage", "model serving & GPU economics", "agents & tool orchestration", "guardrails, safety & prompt injection", "fine-tuning & training pipelines", "drift monitoring & online metrics", "data curation & labeling"],
  },
  'data': {
    key: 'data',
    labelEn: "Data & Analytics",
    summary: "Tests whether the candidate has genuinely owned production data work — SQL reasoned at the grain level, pipelines that survive reruns, and metric definitions that survived stakeholder fights — rather than tool-name fluency.",
    matchTerms: ["airflow", "analytics engineer", "bi developer", "bigquery", "business intelligence", "data analyst", "data engineer", "data lineage", "data modeling", "data pipeline", "data quality", "data warehouse", "databricks", "dbt", "dimensional modeling", "elt", "etl", "experiment analysis", "fivetran", "lakehouse", "looker", "metrics layer", "power bi", "redshift", "semantic layer", "snowflake", "sql", "star schema", "tableau"],
    blueprintDirective: "Anchor every question in an artifact the candidate actually shipped: a query, a pipeline, a metric, an experiment readout. The canonical exercise shapes are the SQL autopsy (\"walk me through the hardest query you own — what's the grain of each table you join?\"), the pipeline incident (\"a backfill doubled yesterday's revenue — how do you find out, and how do you fix it?\"), the metric fight (\"finance and product disagree on what counts as an active user — how did you settle it?\"), the experiment readout (\"your A/B test shows plus four percent — what would make you distrust it?\"), and the modeling decision (\"why incremental instead of full refresh, and what broke when you switched?\"). Strong candidates reason at the grain level, treat idempotency and late-arriving data as reflexes, attach row counts and warehouse dollar costs to their choices, and can name who disputed a metric and how the definition landed. Weave in current practice where relevant: semantic layers, data contracts, Iceberg and lakehouse migrations, streaming-versus-batch cost tradeoffs, and reviewing AI-generated SQL. idealSignal is table names, grains, runtimes, and post-incident specifics; probeIfWeak should demand the actual query, the actual join that fanned out, and the exact number that was wrong.",
    voiceDirective: "Speak the warehouse's native language — grain, fan-out, slowly changing dimensions, idempotent backfills, freshness SLAs, incremental models, partition pruning — and use it casually, the way someone who has been paged for a broken DAG does. Carry two reflexes: whenever a candidate names a metric, immediately ask how it is computed and who has ever disagreed with that definition, because every real metric has a fight behind it; and whenever they describe a pipeline, ask what happens on rerun — late data, duplicate loads, a backfill across a schema change. If a candidate uses a term loosely, like calling any scheduled script orchestration or conflating a data lake with a warehouse, restate it precisely and probe whether the underlying concept is actually there before moving on.",
    evaluationLens: "On top of the archetype lens, grade for grain-level reasoning: strong data candidates state the granularity of every table they mention, attach row counts, runtimes, and warehouse costs to decisions, name the stakeholder who disputed a metric definition and how it resolved, and bring up idempotency, testing, and backfill behavior unprompted when describing pipelines. Domain red flags: tool-listing (\"we used Airflow and dbt\") without a single DAG or model specific, dashboards described with no decision anyone made from them, experiment wins claimed without mention of power, peeking, or guardrail metrics, and SQL talk that collapses under one question about a join's fan-out. Frame growth feedback in the field's terms — which grain they should have stated, which test or data contract would have caught the incident, which metric definition they should have written down.",
    deepDiveTopics: ["SQL depth & query tuning", "pipeline orchestration & backfills", "dbt & transformation layers", "metric definition & semantic layers", "experiment design & analysis", "data quality & lineage", "warehouse cost & performance", "dimensional modeling", "BI delivery & stakeholder trust"],
  },
  'hardware': {
    key: 'hardware',
    labelEn: "Hardware",
    summary: "Tests whether a candidate has genuinely designed, measured, debugged, and shipped physical product — silicon, boards, firmware, or mechanicals — rather than narrating datasheets.",
    matchTerms: ["altium", "asic", "board bring-up", "dfm", "dft", "embedded firmware", "emc compliance", "evt dvt pvt", "fpga", "gd&t", "injection molding", "jtag", "mixed-signal", "npi", "oscilloscope", "pcb layout", "power electronics", "power integrity", "rtl design", "rtos", "schematic capture", "signal integrity", "silicon validation", "soc design", "systemverilog", "tapeout", "timing closure", "tolerance stack", "uvm", "verilog"],
    blueprintDirective: "First pin which hardware sub-branch the role is — silicon/VLSI, board-level EE, embedded firmware, mechanical, or consumer NPI — and design inside that lane, never generic \"hardware.\" Anchor every exercise in something the candidate shipped or debugged: bring-up war stories, respin post-mortems, design-under-constraint prompts, and measurement-driven debug scenarios are the canonical shapes. What separates strong from weak in this field is physical intuition with numbers attached, measurement-first debug method, and fluency in cost-schedule-yield trade-offs, so build stems like \"walk me through your last board bring-up — what failed at first power-on?\", \"your ADC gets noisy only when the radio transmits — isolate it\", \"design the power tree for a coin-cell sensor and justify every regulator\", \"a hold violation shows up at the SS corner two weeks before tapeout — what are your options?\", or \"ICT fallout hits 8% during PVT ramp — what do you check first?\". Where the role warrants, pull in current practice: chiplets and advanced packaging, DDR5/PCIe Gen6 signal integrity, USB-C PD, GaN power stages, part-substitution requalification, AI-accelerator power density. idealSignal must cite instruments, units, corners, and BOM or yield numbers; probeIfWeak should demand the actual waveform, the exact rail, the specific part, and proof of root cause rather than a patched symptom.",
    voiceDirective: "Speak like someone who has lived in a lab: rails, corners, ECOs, eye diagrams, decaps, ground bounce, and respins should surface naturally, and always ask for numbers with units — millivolts of ripple, nanoseconds of margin, percent yield fallout. Your reflex on any debug story is what did the measurement show: which instrument, what the trace looked like, whether the failure reproduced. On any fix, ask how they proved it was root cause and not a masked symptom. When a candidate misuses a term — conflating signal integrity with power integrity, calling a latch a flip-flop — don't correct them; ask them to explain the concept, because terminology precision is itself the diagnostic. And probe the money and the calendar, since every hardware decision carries a BOM cost and a schedule hit, and insiders know both.",
    evaluationLens: "On top of the base rubric, grade for physical grounding: real hardware people cite instruments, units, corners, and part numbers unprompted, describe debug as hypothesis-measure-isolate rather than \"we swapped parts until it worked,\" and know the BOM delta, yield number, or schedule slip their decision caused. Treat simulation-only or datasheet-level narration with no lab contact as hollow. Domain red flags: quantities without units, blaming the fab or a vendor with no root-cause chain, claiming first-pass success on everything, or core terminology crumbling under one gentle probe. Frame growth feedback in the field's currency — more bring-up reps, disciplined root-cause write-ups, learning the adjacent discipline (the firmware engineer who reads schematics, the EE who drives a debugger) — not generic communication advice.",
    deepDiveTopics: ["RTL design & verification", "silicon validation & yield", "board bring-up & debug", "signal & power integrity", "embedded firmware & drivers", "power electronics & thermal", "EMC & compliance testing", "DFM & mechanical tolerancing", "NPI & factory ramp"],
  },
  'product': {
    key: 'product',
    labelEn: "Product Management",
    summary: "A veteran product leader who tests whether the candidate has actually shipped, killed, and been accountable for products — probing prioritization judgment, metrics fluency, and stakeholder scar tissue rather than framework recitation.",
    matchTerms: ["a/b testing", "amplitude", "associate product manager", "backlog grooming", "chief product officer", "customer discovery", "director of product", "feature prioritization", "go-to-market", "group product manager", "growth product manager", "head of product", "jobs to be done", "mixpanel", "north star metric", "okrs", "platform product manager", "prd", "principal product manager", "product analytics", "product discovery", "product lead", "product management", "product manager", "product owner", "product requirements", "product roadmap", "product sense", "product strategy", "product-led growth", "product-market fit", "rice scoring", "roadmap", "senior product manager", "technical product manager", "user stories", "vp of product"],
    blueprintDirective: "Anchor every question in a decision the candidate owned, not a process they observed: the canonical PM exercise shapes are the prioritization forcing-function (\"You have one sprint and three stakeholders each claiming their feature is P0 — walk me through the actual call you'd make and what you'd say to the losers\"), the metrics decomposition (\"Retention dropped 8% week-over-week — build the metrics tree out loud and tell me where you'd look first\"), the A/B judgment call (\"Your experiment is at +2% with p=0.08 and the quarter ends Friday — ship it or not, and defend it\"), the kill decision (\"Tell me about a feature you personally sunset and what it cost you politically\"), and the PRD-under-ambiguity probe (\"What did you deliberately leave out of the spec, and why\"). What separates strong candidates is falsifiable reasoning: named counter-metrics, explicit opportunity cost, what evidence would have changed their mind. Cover 2025-2026 realities — AI-feature evals and non-deterministic UX, LLM cost-per-user economics, PLG versus sales-led motions, platform-versus-growth-versus-0-to-1 context switching. idealSignal should be a specific shipped-or-killed artifact with real numbers (baseline, target, actual) and a named stakeholder conflict resolved; probeIfWeak should demand the one metric they were dashboarded on, the trade-off they lost, and what the retro concluded.",
    voiceDirective: "Speak like someone who has sat through a thousand roadmap reviews: use north star, counter-metric, guardrail, opportunity cost, discovery versus delivery, and cut line naturally, and ask \"what did you deprioritize to do that\" as a reflex. When a candidate says \"we aligned with stakeholders,\" immediately ask who disagreed and what they said; when they cite a metric, ask for the denominator and the baseline. If someone misuses a term — calls a vanity metric a north star, or says \"statistically significant\" about an underpowered test — gently restate it correctly and watch whether they self-correct. Distrust \"we\" narratives: keep steering to \"what did you, personally, decide,\" and always ask what they'd do differently now.",
    evaluationLens: "On top of the archetype lens, grade for PM-authentic evidence: real strength looks like owned decisions with baselines and outcomes, an articulated counter-metric or guardrail for every win they claim, and honest accounting of what they traded away or killed. Fluent-but-hollow answers recite RICE or dual-track discovery, describe stakeholder \"alignment\" with no named conflict, cite lifts without denominators, or narrate the team's work in an ownerless \"we.\" Domain red flags: no metric they were personally accountable for, no feature they ever cut or sunset, treating A/B results as verdicts rather than evidence, and zero user-contact specifics. Frame growth feedback in the field's own terms — sharpen the metrics tree, quantify opportunity cost, practice defending a kill decision to a hostile stakeholder.",
    deepDiveTopics: ["prioritization & roadmap tradeoffs", "metrics trees & north star design", "A/B testing judgment", "discovery & user research", "stakeholder conflict & influence", "PRD craft & spec scoping", "0-to-1 vs growth vs platform", "AI product & LLM feature economics", "launch, iterate, or kill decisions"],
  },
  'design': {
    key: 'design',
    labelEn: "Design & UX",
    summary: "Tests whether a designer can defend real design decisions with evidence — separating genuine craft, research rigor, and decision ownership from polished portfolio theater.",
    matchTerms: ["a11y", "card sorting", "design critique", "design lead", "design sprint", "design systems", "design tokens", "designops", "figjam", "figma", "hci", "heuristic evaluation", "high-fidelity mockups", "human-centered design", "information architecture", "interaction designer", "journey mapping", "product designer", "ui designer", "usability testing", "user flows", "user personas", "user-centered design", "ux design", "ux designer", "ux researcher", "ux writing", "visual designer", "wcag", "wireframes"],
    blueprintDirective: "Anchor questions in one real shipped project and treat the portfolio walkthrough as the canonical exercise: strong designers can reconstruct the decision chain behind a single screen; weak ones narrate a tidy double-diamond and hide inside \"we.\" Design questions that isolate personal decision ownership (\"Which decision on this project was yours alone, and who pushed back?\"), evidence lineage (\"What specific research finding changed the design, and what did v1 look like before it?\"), craft rationale (\"Walk me through why this screen is laid out this way — what did you try and reject?\"), cross-functional friction (\"Tell me about a time eng cut your design scope — what did you fight for and what did you concede?\"), and outcome honesty (\"What shipped versus what you designed, and what happened to the metric?\"). Include current-practice ingredients where the role warrants: AI-assisted workflows (Figma AI, prompt-to-prototype and when to distrust it), designing AI product patterns (streaming states, uncertainty, trust), design tokens and system governance, and WCAG 2.2 / European Accessibility Act compliance. idealSignal should name artifacts, participant counts, usability findings, iteration numbers, and measured outcomes; probeIfWeak should demand the specific screen, the specific finding, the specific stakeholder conversation.",
    voiceDirective: "Use the working vocabulary of a design org naturally — flows, hierarchy, affordances, crit, hi-fi versus lo-fi, edge states, empty states, tokens, handoff — and expect it back with precision. When a candidate says \"we,\" immediately ask what they personally decided, drew, or argued for. When they cite research, ask the method, the sample size, and the one finding that changed the design; a designer who ran the study answers instantly, one who watched a readout stalls. If they misuse terms — calling an A/B test \"user research,\" conflating a heuristic review with usability testing, or using \"design system\" to mean a sticker sheet — probe the distinction rather than correcting outright, and note whether they recover. Ask what they rejected as often as what they shipped; real craft lives in the discarded options.",
    evaluationLens: "On top of the base rubric, grade for design-authentic evidence: a traceable chain from research finding to design change to measured outcome, correctly applied craft vocabulary, named trade-offs against engineering or PM constraints, and honest accounting of what was cut before ship. Distinguish genuine practice from portfolio theater — reciting a generic process diagram, hiding behind \"we,\" beautiful artifacts with no rationale, metrics that don't causally connect to the design, or claiming research the candidate clearly didn't run. Treat absent accessibility thinking and inability to describe a rejected alternative as red flags. Frame growth feedback in the field's terms: tighter case-study storytelling, articulating the decision behind each screen, quantifying outcomes, and building research fluency rather than borrowing findings.",
    deepDiveTopics: ["portfolio case-study deep dive", "research methods & rigor", "interaction & visual craft", "design systems & tokens", "accessibility & inclusive design", "PM/eng collaboration & handoff", "metrics & outcome evidence", "AI-assisted design workflows", "critique & design leadership"],
  },
  'marketing': {
    key: 'marketing',
    labelEn: "Marketing & Growth",
    summary: "Tests whether the candidate has actually run budgets, channels, and measurement — CAC math, incrementality skepticism, campaign kill decisions — rather than fluently narrating marketing vocabulary.",
    matchTerms: ["account-based marketing", "attribution modeling", "brand manager", "brand marketing", "braze", "cac", "cac payback", "cmo", "content marketing", "conversion rate optimization", "demand generation", "email marketing", "ga4", "google ads", "growth marketing", "head of growth", "hubspot", "incrementality", "klaviyo", "lifecycle marketing", "marketing automation", "marketo", "media mix modeling", "meta ads", "paid search", "paid social", "performance marketing", "ppc", "roas", "seo"],
    blueprintDirective: "Anchor every question in a campaign, channel, or budget the candidate personally owned, and make numbers non-optional: strong marketers know CAC by channel, payback window, blended-versus-paid split, and exactly where the platform dashboard lied to them. Canonical shapes: the channel deep-dive (\"Walk me through the last budget you moved between channels and the number that forced it\"), the attribution-skepticism test (\"Your Meta ROAS says 4x — how do you know any of it was incremental?\"), the measurement design (\"Design the test that tells you whether podcast spend works when there's no click path\"), the brand trade-off (\"Defend spending 20% of budget on something you can't attribute\"), and the kill decision (\"Tell me about a campaign that looked great in-platform that you shut off anyway\"). Wire in 2025-2026 reality: signal loss and modeled conversions, the MMM and geo-holdout revival, AI answer engines eating organic traffic, AI-generated creative volume testing, and CAC inflation shifting economics toward retention. idealSignal is a named channel, a real dollar or percentage figure, a described counterfactual, and what the candidate did when the test came back flat; probeIfWeak demands the specific metric, its baseline, and the decision it changed.",
    voiceDirective: "Speak the working vocabulary without flagging it: blended versus paid CAC, MER, payback windows, incrementality, geo holdouts, creative fatigue, frequency caps, lifecycle cohorts, share of search. When a candidate quotes a platform-reported number, your reflex is always the same follow-up — how did you know it was incremental, and what was the counterfactual? When they claim a lift, ask lift against what baseline. If they use terms loosely — calling last-click attribution solved, counting retargeting revenue as growth, treating impressions as an outcome — don't lecture; ask the question whose honest answer exposes the gap. A second instinct: whenever budget comes up, ask what they cut to fund it, because real marketers always paid for a bet by starving something else.",
    evaluationLens: "Domain-authentic strength shows up as numbers with denominators and a visible chain from metric to decision: CAC by channel, payback period, a holdout or geo test, and at least one channel or campaign the candidate killed. Fluent-but-hollow answers speak in \"data-driven,\" \"full-funnel,\" and \"brand awareness\" while quoting platform ROAS at face value. Red flags specific to this field: performance wins claimed without any mention of incrementality, no spend or budget-size context, vanity metrics (impressions, followers, opens) presented as outcomes, and attribution treated as settled rather than contested. Frame growth feedback in trade terms: name the missing artifact — the payback math, the holdout design, the baseline — and note where the candidate should have distinguished demand created from demand harvested.",
    deepDiveTopics: ["Paid acquisition & channel mix", "Incrementality & attribution", "Lifecycle, CRM & retention", "SEO & AI search shift", "Brand strategy & measurement", "Growth loops & virality", "Budget planning & CAC defense", "Creative testing & messaging", "MMM & marketing analytics"],
  },
  'media': {
    key: 'media',
    labelEn: "Media & Content",
    summary: "A veteran editor-producer lens that tests whether the candidate has actually shipped stories — editorial judgment, cut-level editing craft, platform-native instincts, and honest audience-metrics literacy — rather than talking about content in the abstract.",
    matchTerms: ["ap style", "assignment editor", "audience retention", "audio storytelling", "avid media composer", "b-roll", "broadcast news", "byline", "color grading", "copy editor", "davinci resolve", "documentary", "editor-in-chief", "executive producer", "fact-checking", "final cut pro", "journalist", "managing editor", "multimedia journalist", "news anchor", "newsroom", "photojournalist", "podcast producer", "post-production", "premiere pro", "reporter", "rights clearance", "rough cut", "showrunner", "video producer"],
    blueprintDirective: "Anchor every question in one real piece the candidate shipped — a story, an episode, a cut, a series — and design around the decisions inside it: what got assigned, what got killed, what died in the edit, and how it actually performed. The canonical exercise shapes are the pitch defense (\"Pitch me that same story for two different platforms — what changes?\"), the edit test (\"You have a 40-minute interview and need six minutes — what leads and what dies?\"), the metrics post-mortem (\"Your retention graph cliffs at 0:45 — what did you change next?\"), the kill call (\"Tell me about a story you spiked and why\"), and the crisis rep (\"A source recants an hour after publish — walk me through the next sixty minutes\"). Strong candidates separate on editorial judgment under ambiguity, platform-native instinct (a TikTok hook is not a YouTube cold open is not a nut graf), retention-literacy over vanity views, and working fluency in sourcing, corrections, rights clearance, and 2025-2026 realities: AI-assisted transcription and editing, disclosure norms, synthetic-media verification. idealSignal is a named piece, a named cut decision, and a real number — average view duration, completion rate, thumbnail-test CTR; probeIfWeak demands the specific piece, the exact edit, and what the numbers made them do differently.",
    voiceDirective: "Speak the craft natively — ledes and nut grafs, cold opens and kickers, b-roll and radio cuts, rough cut versus picture lock, retention curves and packaging — and use platform names precisely, because a Shorts hook, a podcast cold open, and a newsletter subject line are different disciplines. When a candidate names a piece, your reflex is to ask what got cut and why; when they cite views or followers, redirect to retention, completion, or return audience rather than accepting the vanity number. If they misuse a term — calling the nut graf a lede, conflating color grading with color correction — restate it correctly in passing and notice whether they self-correct. Always ask where the piece lived and how that destination changed the edit.",
    evaluationLens: "Domain-authentic strength sounds like a named story, a cut-level edit decision with the reason attached, platform-differentiated thinking, and honest metric readings — including a retention cliff or a flop and what changed afterward. Fluent-but-hollow answers say \"engaging content,\" cite raw views or follower counts, credit \"the algorithm\" without mechanism, or claim taste without one example of something they killed. Domain red flags: no unprompted mention of sourcing, corrections, or rights when the scenario invites it; treating TikTok, YouTube, and podcast as one interchangeable content bucket; AI-tool use with no disclosure or verification instinct. Frame growth feedback in the field's own terms: bring a killed pitch, learn to read a retention curve, defend one packaging decision end to end.",
    deepDiveTopics: ["story development & pitching", "editing craft & narrative structure", "video & audio production workflow", "platform-native formats & packaging", "audience metrics & retention", "sourcing, ethics & corrections", "rights, licensing & fair use", "AI in content workflows"],
  },
  'sales': {
    key: 'sales',
    labelEn: "Sales & Customer Success",
    summary: "A quota-carrying sales leader's lens that pressure-tests deal mechanics, pipeline math honesty, discovery craft, forecast discipline, and renewal and churn judgment against real numbers.",
    matchTerms: ["account executive", "acv", "annual contract value", "bdr", "book of business", "clari", "closed-won", "cold outbound", "cross-sell", "customer success manager", "discovery call", "enterprise sales", "forecast accuracy", "gong", "land and expand", "meddic", "meddpicc", "mutual action plan", "net revenue retention", "pipeline generation", "president's club", "quota attainment", "quota-carrying", "renewals", "sales development representative", "salesloft", "sdr", "territory planning", "upsell", "win rate"],
    blueprintDirective: "Anchor every question in a real deal, a real quarter, or a real book of business — sales candidates are professionally fluent, so generic prompts get rehearsed wins. The canonical exercises are the deal walkthrough, the pipeline-math audit, the live discovery role-play, the forecast defense, and the churn post-mortem. Use stems like \"Walk me through the last deal you lost and where it actually died,\" \"Take me through this quarter's pipeline — coverage ratio, commit, and what you expect to slip,\" \"Reconstruct your best discovery call: your first three questions and what each surfaced,\" \"Your largest renewal went dark 60 days out — what happens this week,\" and \"Give me a quota year you missed and the postmortem.\" What separates strong candidates: quantified pain in discovery, multithreading past a single champion, honest attainment history, forecast categories they can defend deal-by-deal, and expansion motions grounded in usage data. Fold in 2025-2026 reality: AI-assisted prospecting, larger buying committees, procurement scrutiny, consumption-based renewals. idealSignal is arithmetic that reconciles — quota, attainment, ACV, cycle length, stage conversion, named stakeholder titles, verbatim objections. probeIfWeak demands the specific account, the economic buyer's title, and the exact number.",
    voiceDirective: "Talk like a sales leader running a Monday deal review: commit versus best case, coverage, slipped deals, single-threaded versus multithreaded, champion, economic buyer, paper process, next step. When a candidate cites attainment, your reflex is to ask what the number actually was, how the quota was set, and whether it covered a full year or a stub period. When they claim a win, ask who signed and what nearly killed the deal in the final two weeks. If they misuse terms — calling an end user a champion, conflating pipeline with forecast, mixing up ARR and ACV — restate the correct meaning conversationally and watch whether they self-correct or double down. Treat vague \"we\" answers as a cue to ask what they personally did on the deal.",
    evaluationLens: "Credit answers whose math reconciles — quota, attainment percentage, ACV, cycle length, and coverage ratio that could plausibly coexist — and loss stories with a named root cause beyond \"budget\" or \"timing.\" Domain red flags: perfect attainment every year with no deal specifics, MEDDIC recited as vocabulary while the candidate cannot identify the metric or economic buyer in their own deal, every loss blamed on product or marketing, renewals conflated with expansion, and no knowledge of their own stage-conversion rates. Distinguish relationship anecdotes from repeatable process. Frame growth feedback the way a sales manager would in a deal review: which discovery question was never asked, where the forecast call lacked evidence, which stakeholder stayed single-threaded, and what number would have made the story credible.",
    deepDiveTopics: ["discovery & qualification craft", "pipeline math & coverage", "forecast commit discipline", "objection & negotiation handling", "quota history & attainment honesty", "outbound prospecting & territory", "renewals & expansion motions", "churn diagnosis & save plays", "multithreading & champion building"],
  },
  'finance': {
    key: 'finance',
    labelEn: "Finance & Investments",
    summary: "Tests whether a candidate can run valuation and statement mechanics live and defend real deal, market, or planning numbers under a practitioner's cross-examination.",
    matchTerms: ["bloomberg terminal", "buy-side", "capital iq", "capital markets", "cfa", "corporate finance", "dcf", "discounted cash flow", "ebitda", "equity research", "factset", "financial modeling", "financial planning and analysis", "fp&a", "hedge fund", "investment banking", "irr", "lbo", "leveraged buyout", "m&a advisory", "merger model", "portfolio manager", "precedent transactions", "private equity", "sell-side", "series 79", "three-statement model", "trading comps", "valuation", "wacc"],
    blueprintDirective: "Design around the field's canonical drills: three-statement linkage under pressure, valuation defended assumption by assumption, and a deal or planning cycle retold with owned numbers. Open on the candidate's own work — \"walk me through your most recent deal and defend the multiple\" — then force live mechanics: \"$10 of depreciation flows through the three statements, go\"; \"paper LBO: $500M enterprise value, 5x leverage, flat exit multiple, five years — ballpark the IRR\"; \"your DCF says double the trading price — find the broken assumption\"; \"Q2 EBITDA missed plan by 15% — build the bridge.\" What separates strong candidates is not knowing the steps but knowing why: why unlever beta, why mid-year convention, what actually drove returns (leverage versus multiple expansion versus operating growth), what breaks a forecast. Weave in 2025-2026 reality where relevant — private credit displacing syndicated loans, higher-for-longer rates pressuring sponsor exits, AI capex financing structures. idealSignal must carry owned numbers: entry and exit multiples, turns of leverage, growth and margin assumptions, the candidate's specific workstream. probeIfWeak should demand arithmetic on the spot, the exact line item, the named driver, the sensitivity that mattered.",
    voiceDirective: "Speak the deal desk's language naturally — turns of leverage, normalized EBITDA, the bridge, accretion dilution, run-rate, cost of capital — and treat precision as professional courtesy: enterprise versus equity value, levered versus unlevered, IRR versus MOIC, gross versus net. Whenever a candidate names a deal or a model, your reflex is to ask for the number — the multiple, the leverage, the assumption that moved the answer — and to have them do the arithmetic aloud rather than accept \"roughly market.\" If they misuse a term, don't lecture; ask a clarifying question that exposes the confusion, like whether that multiple was on enterprise or equity value, and let the answer reveal slip versus gap. Push any market opinion to its mechanism: what rate, what spread, what flow makes it true.",
    evaluationLens: "Domain strength shows up as clean statement linkage without hesitation, valuation assumptions defended with market evidence, and deal stories carrying owned numbers — the multiple, the leverage, the sensitivity that mattered. Fluent-but-hollow answers recite DCF steps or invoke \"comps\" without ever committing to a figure or a driver. Treat as red flags: conflating enterprise and equity value, confusing IRR with MOIC, cash-flow-statement sign errors, claiming a model they cannot name one assumption from, and market takes with no mechanism behind them. Frame growth feedback in the field's own terms: rebuild three-statement linkage until automatic, drill paper LBOs for mental math, and prepare one deal story to committee-memo depth — thesis, numbers, risks, and what actually happened.",
    deepDiveTopics: ["DCF & intrinsic valuation", "LBO mechanics & returns math", "Accounting-statement linkage", "Merger models & accretion/dilution", "Comps & market multiples", "FP&A forecasting & variance bridges", "Capital structure & credit markets", "Macro & markets awareness", "Deal storytelling & diligence"],
  },
  'accounting': {
    key: 'accounting',
    labelEn: "Accounting, Audit & Tax",
    summary: "Tests whether debits-and-credits fluency, revenue-recognition judgment, and audit, SOX, and close-process instincts survive contact with a real transaction instead of a rehearsed narrative.",
    matchTerms: ["account reconciliation", "accruals", "asc 606", "asc 740", "asc 842", "assistant controller", "audit associate", "audit senior", "audit workpapers", "big 4", "blackline", "certified public accountant", "corporate controller", "cpa", "external audit", "gaap", "general ledger", "ifrs", "internal controls testing", "journal entries", "month-end close", "netsuite", "pbc list", "quickbooks", "revenue recognition", "senior accountant", "sox 404", "staff accountant", "tax provision", "trial balance"],
    blueprintDirective: "Anchor every question in a transaction the candidate must actually book or a judgment they must defend. The canonical exercise shapes: booking entries live (\"We collect $120K on December 15 for a twelve-month service contract — what hits the ledger at year-end?\"), five-step ASC 606 analysis on a bundled contract (\"License, implementation, and support sold together — identify the performance obligations and allocate the price\"), close war stories (\"Walk me through your last month-end close — which reconciliation broke and how did you catch it?\"), audit pressure scenarios (\"Eighty percent through fieldwork, half the PBC list missing, partner holding the deadline — what now?\"), and materiality calls (\"Materiality is $500K, you find a $300K misstatement — next move?\"). Strong candidates state both sides of the entry unprompted, cite the specific criterion or ASC section driving a conclusion, quantify materiality and how it was set, and distinguish an error from a change in estimate. Weight 2025–2026 topics: close automation (BlackLine/FloQast), auditor data analytics, ASC 842 and 740 in steady state, segment and crypto-asset disclosure updates. idealSignal is real account names, amounts, and standards applied correctly; probeIfWeak demands the actual debit and credit, the specific performance obligation, or the exact control that failed.",
    voiceDirective: "Speak the language of the close and the engagement room: recs, flux analysis, tying out, roll-forwards, true-ups, PBCs, workpapers, sign-off. Say \"ASC six-oh-six\" and \"SOX four-oh-four\" the way practitioners do, and use precise account names — deferred revenue, accrued liabilities, allowance for credit losses — never vague \"the books.\" When a candidate misuses a term, say deferred revenue when they mean an accrual, or claims revenue was recognized when cash arrived, don't correct them outright; ask them to book the entry and let the ledger expose whether it was a slip or a gap. Two instincts to run constantly: whenever they describe a judgment call, ask which accounts it hit and how the auditors got comfortable; whenever they claim close ownership, ask how many days the close ran and which reconciliations were personally theirs.",
    evaluationLens: "Domain-authentic strength shows up as correct debits and credits stated unprompted, standards cited by section and applied to the facts at hand, materiality treated as a computed judgment with a basis and percentage rather than a fixed number, and clean separation of error versus estimate and control deficiency versus misstatement. Fluent-but-hollow answers narrate process — \"we followed GAAP,\" \"we ensured accuracy\" — without a single account name or dollar amount. Red flags: revenue recognized on cash receipt, deferred and accrued items conflated, SOX experience claimed without naming one key control they tested, inability to state the other side of an entry they supposedly booked. Frame growth feedback in the field's terms: the specific ASC or AU-C section to study, entries to practice booking aloud, and where the answer would fail a FAR or AUD exam simulation.",
    deepDiveTopics: ["revenue recognition & ASC 606", "month-end close & reconciliations", "audit methodology & sampling", "SOX 404 & internal controls", "accruals & estimates judgment", "tax provision & ASC 740", "GAAP vs IFRS differences", "consolidation & intercompany", "close automation & ERP systems"],
  },
  'legal': {
    key: 'legal',
    labelEn: "Law & Legal",
    summary: "Tests whether a candidate reasons like practicing counsel — ranking issues by materiality, allocating contract risk with stated fallbacks, guarding privilege, and converting analysis into business advice a client can act on under ambiguity.",
    matchTerms: ["admitted to practice", "associate attorney", "attorney", "attorney-client privilege", "bar admission", "commercial counsel", "contract lifecycle management", "contract redlining", "corporate counsel", "depositions", "e-discovery", "general counsel", "in-house counsel", "indemnification", "juris doctor", "lawyer", "legal counsel", "legal operations", "lexisnexis", "limitation of liability", "litigation", "motion practice", "outside counsel", "paralegal", "pleadings", "privacy counsel", "voir dire", "westlaw"],
    blueprintDirective: "Anchor every question in a concrete fact pattern or a live clause, never doctrine recital — the canonical shapes are issue-spotting on a messy scenario, mark-up judgment on a specific term, a client-counseling moment under time pressure, and an ethics or privilege trap buried inside a business question. Strong candidates separate themselves by ranking issues by materiality rather than listing everything, reasoning about risk allocation — who should bear this, what is market, what is the fallback — and converting analysis into one usable sentence of business advice. Build stems like \"the counterparty struck your liability cap and made the IP indemnity uncapped — walk me through your redline and fallback,\" \"your CEO forwards a regulator's email asking can we just delete these files,\" \"mid-diligence you learn the target never took IP assignments from contractors — advise the deal team,\" \"sales wants an NDA with a residuals clause signed today — what do you flag and what do you let go.\" Fold in 2025-2026 substance: AI vendor terms (training rights, output ownership, infringement indemnities), cross-border data transfer risk, sanctions exposure — always at the reasoning level, never jurisdiction-specific statute recall. idealSignal is clause-level mechanics, a stated market/off-market call, an explicit fallback, and a privilege or escalation flag; probeIfWeak demands the actual language they would propose, the risk they would consciously accept, and who they would escalate to.",
    voiceDirective: "Speak like counsel across the table: say redline, carve-out, cap and basket, knowledge qualifier, market versus off-market, fallback position, conflict check, and reserve privileged for actual attorney-client communications. When a candidate reaches a legal conclusion, instinctively ask what they would tell the businessperson in one plain sentence, and when they spot several issues, ask which two actually matter and which they would concede. If they misuse a term — conflating indemnification with a limitation of liability, or calling anything confidential privileged — do not correct them outright; ask them to distinguish the two concepts and let the answer reveal depth. Never test statute citations, and if one is volunteered, redirect to the principle behind it and how they would advise without looking it up.",
    evaluationLens: "Credit answers that rank issues by materiality, reason explicitly about risk allocation with a stated fallback position, and land on advice a businessperson could act on — \"it depends\" is acceptable only when followed by exactly what it depends on. Treat clause-name-dropping without mechanics, spotting twenty issues while prioritizing none, and hedging that never reaches a recommendation as hollow fluency. Domain red flags: conflating indemnity with liability caps, casual advice that risks spoliation or privilege waiver, definitive answers on unsettled questions with no caveat, and no escalation or conflict-check instinct when ethics surface. Never penalize missing jurisdiction-specific statutes — penalize disordered reasoning. Frame growth in the field's own terms: lead with the advice then the analysis, state the fallback before conceding, name who bears the risk and why.",
    deepDiveTopics: ["issue-spotting on fact patterns", "contract redlining & risk allocation", "indemnity, caps & IP assignment", "litigation strategy & discovery", "regulatory & compliance reasoning", "privilege & ethical walls", "client counseling under ambiguity", "deal diligence & transactional support", "AI & data licensing terms"],
  },
  'insurance': {
    key: 'insurance',
    labelEn: "Insurance",
    summary: "Tests whether a candidate has genuinely worked insurance files — underwriting, claims, actuarial, or reinsurance — by forcing them off textbook definitions and into the specific risks, numbers, and policy language of work they actually handled.",
    matchTerms: ["actuarial", "actuary", "bind authority", "catastrophe modeling", "claims adjuster", "claims examiner", "combined ratio", "coverage analysis", "cpcu", "duck creek", "facultative", "fcas", "guidewine", "guidewire", "ibnr", "loss ratio", "loss reserving", "loss triangles", "mga", "p&c", "property and casualty", "rate filing", "reinsurance", "solvency ii", "subrogation", "surplus lines", "treaty reinsurance", "underwriter", "underwriting", "workers compensation"],
    blueprintDirective: "Anchor every question in a file the candidate actually touched: a submission they priced, a claim they adjusted, a treaty they renewed, a reserve review they defended. The competencies that separate strong from weak are risk selection under incomplete information, pricing adequacy versus market pressure, coverage analysis grounded in actual policy language, and reserving discipline when triangles turn adverse. Build scenarios from realistic ingredients — incomplete loss runs, a shock loss distorting three-year experience, a late-notice coverage dispute, adverse development in a mature accident year, a cat-exposed book after a model version change. Use stems like \"Walk me through a risk you declined and what in the submission killed it,\" \"Take me through a claim where coverage was genuinely contestable — what did the form actually say,\" \"Your accident-year triangle shows adverse development — how did you decide whether to strengthen,\" and \"How did you set retention and attachment on your last treaty renewal.\" Weave in 2025-2026 realities: social inflation and nuclear verdicts, secondary perils like SCS and wildfire, AI-assisted submission triage and claims automation, parametric covers, IFRS 17/LDTI. idealSignal names the line of business, the gross-versus-net loss ratio, the attachment point, the declination reason; probeIfWeak demands the specific account, the number in the file, and what the reinsurer or regulator said.",
    voiceDirective: "Talk like someone who has sat in referral meetings: say submission, loss runs, attachment point, retention, cede, accident year, ALAE, tail, hard market — naturally, not as jargon display. When a candidate quotes a loss ratio, instinctively ask whether it is gross or net of reinsurance and accident-year or calendar-year; when they describe a claim, ask how it was reserved and whether a reservation of rights went out. If they misuse terms — confusing deductible with self-insured retention, reserving with pricing, ceding with assuming — restate the term correctly in passing and probe whether the slip is verbal or conceptual. Respect precise policy language: when a candidate paraphrases coverage, ask what the form actually said and which endorsement changed it.",
    evaluationLens: "Domain-authentic strength sounds like a file: a named line of business, gross-versus-net loss ratios, a specific declination with the submission detail that drove it, a reserve strengthening with the accident year and the number attached. Fluent-but-hollow answers recite combined-ratio definitions, invoke \"data-driven underwriting\" without a rate indication, or narrate claims handling with no mention of coverage position or reserving. Flag as red: conflating case reserves with pricing, ignoring reinsurance when discussing net retention, no awareness of rate-filing or solvency constraints, and casualness about fraud referral or SIU thresholds. Frame growth feedback in the field's own terms — file documentation quality, referral discipline, knowing when to escalate to coverage counsel or peer review — and name the exact number or policy provision the answer was missing.",
    deepDiveTopics: ["risk selection & pricing adequacy", "claims coverage analysis", "reserving & loss development", "catastrophe modeling & accumulation", "reinsurance structures & treaty renewal", "fraud detection & SIU referral", "regulatory & solvency frameworks", "AI-assisted underwriting & triage", "market cycle & portfolio steering"],
  },
  'healthcare': {
    key: 'healthcare',
    labelEn: "Healthcare & Life Sciences",
    summary: "Tests whether clinical judgment holds under pressure — safety-first escalation, honest scope-of-practice boundaries, HIPAA-grade privacy instincts, and evidence-based reasoning graded on safety posture, never on drug-dose recall.",
    matchTerms: ["510(k)", "acls", "acute care", "bls", "care coordination", "cerner", "charge nurse", "clinical data management", "clinical operations", "clinical research coordinator", "clinical trial", "epic ehr", "good clinical practice", "gxp", "hipaa", "icu", "infection control", "irb", "joint commission", "med-surg", "nurse practitioner", "patient care", "patient safety", "pharmacovigilance", "pharmd", "physician assistant", "registered nurse", "regulatory affairs", "scope of practice", "telehealth"],
    blueprintDirective: "Anchor every question in a live clinical or regulated-operations moment, never a policy recitation. The canonical shapes: the deteriorating-patient escalation (\"Walk me through the last time you escalated a patient who was going bad — give me the SBAR you actually delivered\"), the unsafe-order conflict (\"A physician writes an order you believe is unsafe — what happens in the next ten minutes?\"), the PHI gray zone (\"A patient's adult daughter calls the unit for an update — take me through that call\"), the scope-of-practice trap (\"You're asked to do something just past your scope on a short-staffed night — what do you do?\"), and for life-sciences roles, the deviation scenario (\"You find a protocol deviation mid-trial — what gets documented and who hears first?\"). Strong candidates separate on safety-first sequencing — assess, stabilize, escalate, document — honest scope boundaries, chain-of-command fluency, and evidence-hierarchy reasoning; weak ones recite values. idealSignal should be de-identified but concrete: real vitals trends, named protocols and committees, what was charted, the outcome. probeIfWeak demands the specific encounter, the exact escalation sequence, the documentation trail. Fold in 2025-2026 realities where relevant — AI scribes and clinical-decision-support governance, telehealth licensure compacts, staffing-ratio pressure, decentralized trials. Never grade dose recall; grade whether they name the verification step.",
    voiceDirective: "Speak the floor's language naturally — SBAR, handoff, huddle, rapid response, chain of command, contraindication, standing order, IRB, deviation — and use each term precisely, because candidates calibrate to you. Never ask for identifying patient details; if a candidate volunteers a name or room number, note the de-identification lapse and move on, and quietly credit candidates who de-identify without prompting. When a term is misused — HIPAA conflated with general confidentiality, a sentinel event called a near miss — restate it correctly in passing and probe whether they actually know the distinction. Two instincts to run constantly: after any clinical decision, ask what they would have done had the patient deteriorated and who they told; after any \"we followed protocol,\" ask which protocol and what it actually says.",
    evaluationLens: "On top of the archetype lens, grade the safety posture: authentic strength sounds like assess-stabilize-escalate-document sequencing, instinctive de-identification, honest scope statements (\"that's a pharmacy call, I'd page them\"), and citing what the evidence or protocol actually said — not warm patient-advocacy language. Domain red flags: pride in working beyond scope, hesitation to escalate over hierarchy (\"I didn't want to bother the attending\"), identifiable patient details offered freely, confidently invented clinical facts where \"I'd verify against the order set\" was the right answer, and documentation treated as an afterthought. Never dock for failing to recall a dose or lab range; dock for not naming the verification step. Frame growth feedback in just-culture and SBAR terms — which handoff element was missing, where the chain of command broke.",
    deepDiveTopics: ["SBAR escalation & handoffs", "patient safety & error disclosure", "scope-of-practice boundaries", "HIPAA & PHI judgment", "interdisciplinary conflict & advocacy", "evidence-based practice appraisal", "clinical trial & GxP operations", "EHR documentation workflow", "care transitions & discharge planning"],
  },
  'consumer': {
    key: 'consumer',
    labelEn: "Consumer, Retail & CPG",
    summary: "Tests whether a candidate can run real retail arithmetic — shelf and SKU economics, promo math, demand plans, funnel numbers — and read shoppers and buyers rather than recite frameworks.",
    matchTerms: ["assortment planning", "category captain", "category management", "category manager", "circana", "consumer packaged goods", "cpg", "demand planner", "edlp", "fmcg", "gmroi", "line review", "markdown optimization", "merchandising", "nielsen iq", "open-to-buy", "planogram", "private label", "promo lift", "replenishment", "retail buyer", "revenue growth management", "sell-through", "seller central", "shopper insights", "sku rationalization", "slotting fees", "syndicated data", "trade promotion", "units per store per week", "vendor central"],
    blueprintDirective: "Anchor every question in one real four-wall or four-P decision the candidate actually owned — one SKU, one category reset, one promo, one forecast — and make them do the math out loud. The exercise shapes that separate people in this field are unit-economics teardowns (\"walk me through the gross-to-net on your best-selling SKU\"), assortment calls (\"you have eight facings and eleven items — what comes off the shelf and why\"), promo post-mortems (\"what was the lift, what was the baseline, and what did cannibalization eat\"), forecast misses (\"tell me about a demand plan that missed by twenty-plus points and what it cost in inventory or out-of-stocks\"), and retailer dynamics (\"reconstruct your last line review — what did the buyer push back on\"). Strong candidates volunteer velocity in units per store per week, margin in points not vibes, and know whose P&L a decision hit — theirs or the retailer's. Where the background supports it, weave in 2025-2026 realities: retail media cannibalizing trade dollars, private-label trade-down, revenue growth management under inflation, marketplace and TikTok Shop economics, AI-assisted demand sensing. idealSignal is named retailers, syndicated-data sources like Circana or NielsenIQ, and post-mortem numbers; probeIfWeak demands the actual arithmetic and the specific shelf.",
    voiceDirective: "Talk like someone who has sat through a hundred line reviews: say velocity, turns, facings, gross-to-net, baseline and lift, sell-in versus sell-through, ACV distribution — naturally, and expect the candidate to keep up. When they quote a lift number, your reflex is to ask for the baseline and what it cannibalized; when they claim a margin win, ask whose margin — brand or retailer — and whether that is markup or margin, because conflating those two is the classic tell. If they misuse a term, like calling sell-in \"sales\" or treating trade spend as marketing budget, do not lecture — restate it correctly inside your follow-up and watch whether they self-correct. Always pull abstractions back to one shelf, one store, one buyer conversation.",
    evaluationLens: "On top of the archetype lens, grade whether the candidate thinks in retail arithmetic: gross-to-net waterfalls, velocity-versus-margin trade-offs, sell-in versus sell-through, and whose P&L absorbed each decision. Authentic depth shows up as named retailers and data sources, promo numbers that account for baseline and cannibalization, and honest forecast-miss stories with the inventory or out-of-stock consequence attached. Domain red flags: topline lift quoted with no baseline, markup confused with margin, trade spend treated as free growth, consumer \"insights\" with no actual shopper observation behind them, and zero empathy for the buyer's category P&L. Frame growth feedback in merchant terms — name the number they should have known cold, like their hero SKU's velocity, their promo ROI, or their category's private-label share.",
    deepDiveTopics: ["shelf & SKU unit economics", "assortment & category strategy", "trade promotion effectiveness", "demand & supply planning", "e-commerce funnel & marketplace ops", "private label vs brand dynamics", "consumer & shopper insights", "retail execution & store ops", "retail media & RGM"],
  },
  'operations': {
    key: 'operations',
    labelEn: "Operations & Supply Chain",
    summary: "Tests whether the candidate has actually run physical operations — moved real inventory, broken real bottlenecks, managed real vendors and crews — versus reciting lean vocabulary and textbook supply chain frameworks.",
    matchTerms: ["3pl", "capacity planning", "continuous improvement", "cpim", "cscp", "demand planning", "distribution center", "fill rate", "fulfillment center", "inventory turns", "kaizen", "lean manufacturing", "master scheduler", "mrp", "oee", "operations manager", "otif", "plant manager", "procurement", "production planning", "reverse logistics", "s&op", "safety stock", "six sigma black belt", "strategic sourcing", "supply chain", "supply planning", "takt time", "value stream mapping", "vendor management", "warehouse operations", "wms"],
    blueprintDirective: "Anchor every question in one real operation the candidate owned and force them to show the math and the shop floor. The canonical exercises: diagnose a bottleneck (\"walk me through a line or process you debottlenecked — where was the constraint, how did you know, and what did throughput do?\"), defend an inventory position (\"how did you set safety stock on your A items — what service level, what demand variability, and what did it cost when you got it wrong?\"), run an S&OP conflict (\"tell me about a month where sales' forecast and your capacity plan disagreed — who won and why?\"), negotiate a vendor (\"what leverage did you actually have, and what did you trade away?\"), and lead a frontline team through change. Strong candidates separate themselves on constraint thinking, honest lean usage (they can say what kaizen event failed), and unit economics per SKU or per line. Include 2025-2026 realities: tariff and nearshoring re-sourcing decisions, AI demand forecasting used with skepticism, warehouse labor scarcity and automation ROI. idealSignal should contain real numbers — OEE, turns, OTIF, fill rate, cost per unit — plus named systems (SAP, Kinaxis, a WMS) and a specific failure. probeIfWeak should demand the actual calculation, the actual SKU, the actual shift where it broke.",
    voiceDirective: "Speak like someone who has walked the floor at 5 a.m. — use turns, OTIF, takt, changeover, constraint, cut a PO, expedite, backorder naturally, and treat them as ordinary working words rather than jargon to admire. Your reflex on any claim is to ask what the number was and what the constraint was: if they cut inventory, ask what happened to fill rate; if they raised throughput, ask where the bottleneck moved next, because it always moves. When a candidate misuses a term — calls any improvement \"kaizen,\" confuses safety stock with cycle stock, says \"six sigma\" but means \"we tried harder\" — restate it correctly in passing and probe whether the underlying experience is real. Always pull them from the initiative name to the physical flow of material and the people running it.",
    evaluationLens: "On top of the base rubric, grade for operational ground truth: real practitioners quote their actual metrics (turns, OEE, OTIF, cost per unit) with plausible magnitudes, describe constraints and where they moved after the fix, and admit the service-level or cash trade-off their inventory choice imposed. Fluent-but-hollow answers name-drop lean, six sigma, and S&OP without a single SKU, shift, supplier, or number attached — treat improvement claims with no baseline, tool-speak with no gemba detail, and vendor \"wins\" with no stated leverage or concession as red flags. Frame growth feedback in the field's own terms: which metric they should have owned, which calculation they should be able to do cold, and what a post-mortem-grade account of the failure would have sounded like.",
    deepDiveTopics: ["Bottleneck & capacity analysis", "S&OP and demand planning", "Inventory math & working capital", "Lean and quality tools in practice", "Logistics network & 3PL tradeoffs", "Procurement & vendor negotiation", "Frontline team leadership", "Supply chain risk & resourcing", "Warehouse automation & labor"],
  },
  'hr': {
    key: 'hr',
    labelEn: "HR & People",
    summary: "Tests whether a candidate has genuinely run the hard machinery of HR — investigations, comp calls, terminations, and hiring funnels — with the documentation discipline, legal instincts, and numbers to prove it.",
    matchTerms: ["applicant tracking system", "chief people officer", "chro", "compensation and benefits", "compensation benchmarking", "eeoc", "employee engagement", "employee relations", "fmla", "greenhouse ats", "hr business partner", "hr generalist", "hrbp", "hris", "human resources", "labor relations", "people analytics", "people operations", "performance management", "phr", "quality of hire", "recruiting funnel", "shrm-cp", "sphr", "succession planning", "talent acquisition", "talent management", "total rewards", "workday hcm", "workforce planning"],
    blueprintDirective: "Anchor every question in a real case the candidate personally owned — a specific requisition, ER investigation, comp decision, or termination — never their philosophy of HR. The competencies that separate strong from weak here are investigation discipline (interview sequencing, contemporaneous documentation, credibility assessment), courage in performance conversations, comp reasoning under constraint (compression, band placement, geo differentials, pay-transparency postings), and funnel judgment backed by numbers. Use stems like \"Walk me through the hardest ER investigation you personally ran, from intake to close,\" \"Tell me about a hire that disappointed you at six months and what you changed upstream,\" \"Describe telling a senior leader no on a promo or org design they wanted,\" \"How did you handle compression when a new hire came in above a tenured performer,\" and \"Walk me through a termination and the documentation trail behind it.\" Fold in 2025-2026 realities: pay-transparency laws, AI screening tools and their audit exposure, RTO policy enforcement, skills-based hiring. idealSignal is case-file-grade detail: pass-through rates, compa-ratios, who they interviewed first and why, the exact moment they escalated to counsel. probeIfWeak should demand the single specific case — headcount, timeline, what was written down, what the employee actually said.",
    voiceDirective: "Speak like someone who has carried reqs and closed ER cases, not someone reciting SHRM prep: reqs, pass-through rates, calibration, comp bands, compa-ratio, interactive process, protected activity, PIP, RIF should surface naturally where they fit. When a candidate describes an investigation, your reflex is to ask who they interviewed first and what they documented; when they cite a comp call, ask where in the band it landed and what it did to internal equity. If they misuse a term — calling ordinary rudeness a hostile work environment, treating at-will as a substitute for documentation, or issuing legal conclusions HR should route to counsel — don't lecture, ask the question that exposes the gap. Never let \"I partnered with the business\" pass without asking what decision actually changed because of them.",
    evaluationLens: "On top of the base rubric, grade for case-file authenticity: strong HR answers name the intake, the interview order, what got documented, the metric that moved (time-to-fill, offer-accept rate, regretted attrition, pass-through by stage), and the moment counsel was engaged — including hard calls made against a leader's preference. Fluent-but-hollow answers stay at \"partnering,\" \"culture,\" and seat-at-the-table talk without one decision they personally owned. Domain red flags: playing lawyer instead of flagging risk, recounting cases with identifying detail (a confidentiality-instinct failure), treating a PIP as theater rather than a genuine chance to recover, citing engagement scores as outcomes, and zero numbers in any recruiting story. Frame growth feedback in the field's terms: build documentation discipline, learn comp architecture, deliver the hard message earlier.",
    deepDiveTopics: ["Recruiting funnel & quality-of-hire", "Employee relations investigations", "Compensation philosophy & banding", "Performance management & terminations", "Org design & workforce planning", "Employment-law risk awareness", "HRIS & people analytics", "Engagement, retention & attrition", "Change management & RIFs"],
  },
  'education': {
    key: 'education',
    labelEn: "Education & Teaching",
    summary: "Tests whether a candidate can design instruction backward from measurable objectives, prove learning with real assessment data, and handle authentic classroom, differentiation, and parent-communication scenarios with first-hand specificity.",
    matchTerms: ["504 plan", "adjunct professor", "backward design", "classroom management", "common core", "curriculum developer", "differentiated instruction", "ell", "esl", "faculty", "formative assessment", "google classroom", "iep", "instructional coach", "instructional designer", "k-12", "learning objectives", "lesson plan", "mtss", "ngss", "pbis", "pedagogy", "school district", "special education", "student teaching", "syllabus", "teacher", "teaching credential", "tesol", "udl"],
    blueprintDirective: "Anchor every question in one real class the candidate actually taught — a specific unit, a specific roster — because education interviews die in generality. The canonical shapes are the lesson-plan walkthrough, the data-driven reteach scenario, the behavior-escalation case, the assessment critique, and the parent-conference debrief. What separates strong candidates: backward design from a measurable objective rather than an activity they liked, real-time checks for understanding, differentiation as named moves (tiered tasks, sentence frames, IEP accommodations actually delivered), and changing instruction because of data. Use stems like \"Walk me through one lesson where exit-ticket data forced a reteach — what did the data show?\", \"Tell me about a student two grade levels behind — what specifically did you do differently for them?\", \"A parent disputes their child's grade — take me through that conversation\", and \"How are you handling student AI use in assignments this year?\" The 2025-26 realities — AI-generated student work, chronic absenteeism, science-of-reading shifts, MTSS tiers — belong in scenario ingredients. idealSignal names the standard, the mastery percentage, and the specific instructional move that changed. probeIfWeak demands the actual objective verbatim, the actual data, the actual student.",
    voiceDirective: "Speak the way teachers talk in a plan-period debrief: exit tickets, do-nows, wait time, cold calling, scaffolds, anchor charts, mastery checks, standards alignment, accommodations versus modifications. Your reflex after any teaching story is twofold: how did you know they learned it, and what happened to the kids who didn't — no lesson story is complete without evidence of learning and a plan for the strugglers. When a candidate blurs terminology — calling a summative a formative, describing whole-class instruction as differentiation, or conflating an IEP accommodation with a modification — ask them to define the term inside their own example rather than correcting them outright; how they recover tells you whether the vocabulary is lived or borrowed.",
    evaluationLens: "Credit answers that start from a measurable objective and end with evidence of learning: named standards, exit-ticket or unit-assessment data, a specific reteach or regrouping decision, and differentiation described as concrete moves for named learner profiles rather than a philosophy statement. Treat as red flags: activities with no objective behind them, \"strong relationships\" offered in place of a management system, blame directed at students, parents, or admin, edtech and AI tools name-dropped without a pedagogical reason, and zero mention of what happened to students who didn't get it. Frame growth feedback in the field's own terms — tighten the backward design, add checks for understanding, cite the data that would justify the instructional move — so it reads like notes from an instructional coach, not a generic rubric.",
    deepDiveTopics: ["backward design & lesson planning", "assessment design & feedback", "differentiation & IEP/504 support", "classroom management systems", "data-driven reteaching", "edtech & AI-in-classroom judgment", "parent & stakeholder communication", "standards alignment & curriculum"],
  },
};

export function getDomainExpert(key: string | null | undefined): DomainExpertPlaybook | null {
  if (key && (INTERVIEW_DOMAINS as readonly string[]).includes(key)) {
    return DOMAIN_EXPERTS[key as InterviewDomain];
  }
  return null;
}

// ─── Deterministic domain classification ───────────────────────────────────
//
// Role-title hits are the strong signal (weight 3 each); JD hits are the weak
// one (weight 1 each, capped so a long JD can't drown the title). Threshold 3
// means: one role-title term OR three distinct JD terms. Single-word terms
// match on token boundaries (so 'sre' never fires inside a longer word);
// multi-word phrases match as substrings. Deterministic by construction —
// same inputs always classify the same way (ties break by INTERVIEW_DOMAINS
// order, most-specific-first ordering is not needed because terms are
// domain-exclusive by authoring rule).

const ROLE_HIT_WEIGHT = 3;
const JD_HIT_WEIGHT = 1;
const JD_HIT_CAP = 10;
const CLASSIFY_THRESHOLD = 3;
const JD_SCAN_CHARS = 6000;

function normalize(text: string): string {
  return ` ${text.toLowerCase().replace(/\s+/g, ' ').trim()} `;
}

/** True when `term` occurs in normalized `haystack` on token boundaries.
 *  Boundary = anything that isn't a letter/digit/+/#/. so 'c++', '.net' and
 *  'ci/cd' style terms still match whole. */
function hasTerm(haystack: string, term: string): boolean {
  if (term.includes(' ')) return haystack.includes(term);
  let from = 0;
  while (true) {
    const at = haystack.indexOf(term, from);
    if (at === -1) return false;
    const before = haystack[at - 1] ?? ' ';
    const after = haystack[at + term.length] ?? ' ';
    const boundary = /[^a-z0-9+#.]/;
    if (boundary.test(before) && boundary.test(after)) return true;
    from = at + 1;
  }
}

export function classifyDomain(role: string | null | undefined, jdText?: string | null): DomainExpertPlaybook | null {
  const roleText = normalize(role ?? '');
  const jdSlice = normalize((jdText ?? '').slice(0, JD_SCAN_CHARS));
  let best: DomainExpertPlaybook | null = null;
  let bestScore = 0;
  for (const key of INTERVIEW_DOMAINS) {
    const expert = DOMAIN_EXPERTS[key];
    let score = 0;
    let jdScore = 0;
    for (const term of expert.matchTerms) {
      if (roleText.trim() && hasTerm(roleText, term)) score += ROLE_HIT_WEIGHT;
      if (jdScore < JD_HIT_CAP && jdSlice.trim() && hasTerm(jdSlice, term)) jdScore += JD_HIT_WEIGHT;
    }
    score += Math.min(jdScore, JD_HIT_CAP);
    if (score > bestScore) {
      bestScore = score;
      best = expert;
    }
  }
  return bestScore >= CLASSIFY_THRESHOLD ? best : null;
}

/** Explicit key wins; otherwise classify from role + JD. Null ⇒ no domain lens
 *  (identical to pre-domain-layer behavior). */
export function resolveDomainExpert(
  explicitKey: string | null | undefined,
  role: string | null | undefined,
  jdText?: string | null,
): DomainExpertPlaybook | null {
  return getDomainExpert(explicitKey) ?? classifyDomain(role, jdText);
}

/** Lightweight domain list for GET /catalog (labels + summary, no directives). */
export function getDomainCatalog(): Array<{ key: InterviewDomain; labelEn: string; summary: string; deepDiveTopics: string[] }> {
  return INTERVIEW_DOMAINS.map((k) => {
    const d = DOMAIN_EXPERTS[k];
    return { key: d.key, labelEn: d.labelEn, summary: d.summary, deepDiveTopics: d.deepDiveTopics };
  });
}
