#!/usr/bin/env tsx
/**
 * Render the LLM cost table (server/src/lib/modelCostTable.ts) as markdown.
 *
 *   npm run llm:costs            # print to stdout
 *   npm run llm:costs -- --write # refresh docs/LLM_COSTS.md
 *   npm run llm:costs -- --check # fail if docs/LLM_COSTS.md is stale (npm run check)
 *
 * The table in code is the source of truth; this only renders it, so the doc
 * can never drift from what the biller actually charges. It also reports which
 * of the models this environment is CONFIGURED to call have no priced row —
 * those bill at the default tier and silently mis-report platform spend.
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import dotenv from 'dotenv';

import {
  AUDIO_MODEL_COST_TABLE,
  DEFAULT_MODEL_COST,
  MODEL_COST_TABLE,
  buildCostLookup,
  idsForRow,
} from '../server/src/lib/modelCostTable.js';

const REPO_ROOT = resolve(fileURLToPath(new URL('../', import.meta.url)));

// Same load order as server/src/app.ts, so the coverage check below sees the
// model selectors this machine actually runs with.
dotenv.config({ path: resolve(REPO_ROOT, '.env'), override: false, quiet: true });
dotenv.config({ path: resolve(REPO_ROOT, '.env.local'), override: false, quiet: true });

/** Model-selector env vars, in the order the config docs list them. */
const MODEL_ENV_VARS = [
  'LLM_MODEL',
  'LLM_FALLBACK_MODEL',
  'LLM_MATCHING_MODEL',
  'LLM_EXTRACT_MODEL',
  'LLM_VISION_MODEL',
  'LLM_ONBOARDING_MODEL',
  'LLM_REWRITE_MODEL',
  'LLM_INTERVIEW_MODEL',
];

const { pricing } = buildCostLookup(MODEL_COST_TABLE);

/** `$0.375` — trims the trailing zeros a fixed precision would add. */
const usd = (n: number): string => `$${Number(n.toFixed(6))}`;

/**
 * A configured selector carries a leading routing hint the pricing path never
 * sees (`openrouter/openai/gpt-5.6-luna` is billed as `openai/gpt-5.6-luna`
 * once LLMService has resolved the provider). Strip it the same way, so this
 * check reflects what will actually be billed.
 */
function billingIdFor(selector: string): string {
  const id = selector.trim().replace(/^models\//i, '');
  if (pricing[id]) return id;
  const cut = id.indexOf('/');
  if (cut > 0) {
    const rest = id.slice(cut + 1);
    if (rest.includes('/') && pricing[rest]) return rest;
    // `gemini/…` is an accepted direct-provider alias for `google/…`.
    if (id.startsWith('gemini/') && pricing[`google/${rest}`]) return `google/${rest}`;
    if (rest.includes('/')) return rest;
  }
  return id;
}

function render(): string {
  const out: string[] = [];

  out.push('# LLM cost table');
  out.push('');
  out.push(
    '<!-- GENERATED by `npm run llm:costs -- --write`. Do not edit by hand: change',
  );
  out.push('     the rates in server/src/lib/modelCostTable.ts and regenerate. -->');
  out.push('');
  out.push(
    'Every per-token rate the platform bills with, in USD per 1,000,000 tokens. ' +
      'The rates live in [`server/src/lib/modelCostTable.ts`](../server/src/lib/modelCostTable.ts); ' +
      '`modelPricing.ts` derives the lookup and the costing math from them, and ' +
      '`LoggerService.logLLMCall` prices every call through that path.',
  );
  out.push('');
  out.push('## Token models');
  out.push('');
  out.push('| Model | Input $/1M | Output $/1M | Also billed as | Notes |');
  out.push('| --- | ---: | ---: | --- | --- |');
  for (const row of MODEL_COST_TABLE) {
    const alsoAs = idsForRow(row)
      .filter((id) => id !== row.id)
      .map((id) => `\`${id}\``)
      .join(', ');
    out.push(
      `| \`${row.id}\` | ${usd(row.input)} | ${usd(row.output)} | ${alsoAs || '—'} | ${row.note ?? ''} |`,
    );
  }
  out.push('');
  out.push(
    `**Unpriced models** fall back to ${usd(DEFAULT_MODEL_COST.input)} in / ` +
      `${usd(DEFAULT_MODEL_COST.output)} out per 1M, and \`calculateModelCost\` warns ` +
      'once per unknown id. **OpenRouter `:free` variants** bill at $0 by rule, ' +
      'whether or not they have a row.',
  );
  out.push('');
  out.push('## Audio models (per minute)');
  out.push('');
  out.push('| Model | $/min |');
  out.push('| --- | ---: |');
  for (const [model, rate] of Object.entries(AUDIO_MODEL_COST_TABLE)) {
    out.push(`| \`${model}\` | ${usd(rate)} |`);
  }
  out.push('');
  out.push('## Keeping this current');
  out.push('');
  out.push('1. Edit the row in `server/src/lib/modelCostTable.ts`.');
  out.push('2. `npm run llm:costs -- --write` to regenerate this file.');
  out.push('3. `npx vitest run server/src/lib/modelCostTable.test.ts`.');
  out.push('');
  out.push(
    'A price change is **forward-only**: historical `UsageDeductionLog.platformCostUsd`, ' +
      '`LLMCallLog.cost` and `InterviewSession.costBreakdown` rows are denormalized at ' +
      'write time and are never recomputed.',
  );
  out.push('');
  out.push(
    'An admin-saved `rate_card.{env}` row in `AppConfig` deep-merges **over** these ' +
      'constants for the admin rate-card panel, so a stale override there keeps ' +
      'displaying the old rate after a bump — clear the repriced model out of that blob.',
  );
  out.push('');

  return out.join('\n');
}

/** Which configured selectors would bill at the default tier. */
function reportConfiguredCoverage(): void {
  const configured = MODEL_ENV_VARS.map((name) => [name, (process.env[name] ?? '').trim()] as const)
    .filter(([, value]) => value.length > 0);

  if (configured.length === 0) {
    console.error('\n(no LLM_*_MODEL env vars set — skipping the coverage check)');
    return;
  }

  console.error('\nConfigured models in this environment:');
  let gaps = 0;
  for (const [name, selector] of configured) {
    const id = billingIdFor(selector);
    const rate = pricing[id];
    if (rate) {
      console.error(`  ok   ${name}=${selector}  →  ${usd(rate.input)}/${usd(rate.output)} per 1M`);
    } else {
      gaps += 1;
      console.error(
        `  GAP  ${name}=${selector}  →  no row for "${id}", bills at the ` +
          `${usd(DEFAULT_MODEL_COST.input)}/${usd(DEFAULT_MODEL_COST.output)} default`,
      );
    }
  }
  if (gaps > 0) {
    console.error(`\n${gaps} configured model(s) have no cost-table row — add them.`);
  }
}

const DOC_PATH = resolve(REPO_ROOT, 'docs/LLM_COSTS.md');
const markdown = `${render()}\n`;

if (process.argv.includes('--check')) {
  // Every price edit must show up as a diff in the committed table — otherwise
  // a rate can change with nothing reviewable outside the constants file.
  const onDisk = existsSync(DOC_PATH) ? readFileSync(DOC_PATH, 'utf8') : '';
  if (onDisk !== markdown) {
    console.error(
      '✗ docs/LLM_COSTS.md is out of date with server/src/lib/modelCostTable.ts.\n' +
        '  Run: npm run llm:costs -- --write',
    );
    process.exit(1);
  }
  console.log(`✓ LLM cost table clean — ${MODEL_COST_TABLE.length} models, docs in sync`);
} else if (process.argv.includes('--write')) {
  writeFileSync(DOC_PATH, markdown, 'utf8');
  console.error(`Wrote ${DOC_PATH} (${MODEL_COST_TABLE.length} models).`);
  reportConfiguredCoverage();
} else {
  console.log(markdown);
  reportConfiguredCoverage();
}
