// lib/api/v2/raV2Api.ts
//
// Single typed API surface for RoboApply V2. F2-F5 (every page engineer)
// import the `RaV2Api` interface from here when they need to type a parameter
// or pass the api object around. The actual runtime instance is exported as
// the default named export `raV2Api` from `./index.ts` and is selected at
// module-load time by the env flag (`NEXT_PUBLIC_USE_STUB_API`).
//
// Why a dedicated re-export file (not just `types.ts`):
// Wave 4's swap is: same `RaV2Api` shape, two implementations. Having one
// file whose ONLY job is to expose the surface keeps the contract tight —
// any drift between `realApi` and `stubApi` becomes a compile error here.

export type {
  RaV2Api,
  DiscoverRunBody,
  CrossBankDiscoverResponse,
  DiscoverJobCard,
  CrossBankCoverageStats,
  BankId,
  AcceptanceBand,
  MatchTier,
  // Re-export the major shapes so call sites don't need a second import
  // when they only need the API + the shape of one of its arguments.
  RACareerGoal,
  RAJob,
  RAJobListItem,
  RATrackerStatus,
  RATrackerEntryView,
  RAJobMatchScoreView,
  RAResumeVariant,
  RAResumeVariantSummary,
  RAResumeKind,
  RASavedSearch,
  RACareerInsight,
  RAKeyword,
  RAKeywordImportance,
  RAWorkType,
  RAEmploymentType,
  RASortBy,
  RAAppliedVia,
  RASeniority,
  RAJobTier,
  RADatePosted,
  RASourceBoard,
  RASalaryPeriod,
  SearchQuery,
  SearchRunParams,
  GoalUpsertBody,
  TrackerListParams,
  TrackerCreateBody,
  TrackerPatchBody,
  TrackerBulkBody,
  JobGetParams,
  JobApplyBody,
  JobScoreBody,
  ResumeCreateBody,
  ResumePatchBody,
  InsightsWeeklyParams,
  GoalGetResponse,
  GoalUpsertResponse,
  TrackerListResponse,
  TrackerGetResponse,
  TrackerCreateResponse,
  TrackerPatchResponse,
  TrackerBulkResponse,
  SearchRunResponse,
  SearchSaveQueryResponse,
  SearchListSavedResponse,
  JobGetResponse,
  JobApplyResponse,
  JobSaveResponse,
  JobScoreResponse,
  ResumeListResponse,
  ResumeCreateResponse,
  ResumeGetResponse,
  ResumePatchResponse,
  LinkedInImportConfigResponse,
  LinkedInImportArgs,
  InsightsWeeklyResponse,
  InsightsRefreshResponse,
  // ── V3 enums ──
  RAQueueItemStatus,
  RAActivityKind,
  RAResumeRewriteAction,
  RAResumeRewriteMode,
  RATailorChangeKind,
  RAMockFormat,
  RAMockSpeaker,
  RAIntegrationProvider,
  RAAggressiveness,
  // ── V3 entities ──
  RAQueueCheck,
  RAQueueItem,
  RAActivityEntry,
  RAActivityDay,
  RAAgentStats,
  RAMockInterviewer,
  RAMockType,
  RAMockRoleCategory,
  RAMockCatalog,
  RAMockSessionSummary,
  RAMockTurn,
  RAMockCoachTip,
  RAIntegration,
  RAPreferences,
  RAPreferenceOptions,
  RATailorChange,
  RATailorDiff,
  RAResumeCoachTip,
  // ── V3 request shapes ──
  QueueUpdateCoverBody,
  ActivityFeedParams,
  MockStartBody,
  MockNextTurnBody,
  ResumeRewriteBody,
  ResumeTailorDiffBody,
  PreferencesUpdateBody,
  // ── V3 response shapes ──
  QueueListResponse,
  QueueItemResponse,
  ActivityFeedResponse,
  AgentStatsResponse,
  MockCatalogResponse,
  MockRecentSessionsResponse,
  MockStartResponse,
  MockNextTurnResponse,
  MockScoreResponse,
  IntegrationsListResponse,
  IntegrationResponse,
  PreferencesGetResponse,
  PreferencesUpdateResponse,
  ResumeRewriteResponse,
  ResumeTailorDiffResponse,
  ResumeCoachTipsResponse,
  // ── Onboarding Chat v4 ──
  RAOnboardingState,
  RAOnboardingStatusKey,
  RAOnboardingStreamEvent,
  RAOnboardingQuickReply,
  IngestRow,
  OnboardingDraftPreferences,
  OnboardingDraftSalary,
  OnboardingDraftLocations,
  OnboardingJobCard,
  OnboardingBootstrapBody,
  OnboardingBootstrapResponse,
  OnboardingChatStreamBody,
  OnboardingTranscriptMessage,
  OnboardingSessionResponse,
  OnboardingCompleteBody,
  OnboardingCompleteResponse,
  OnboardingSkipBody,
  OnboardingSkipResponse,
  OnboardingPassBody,
  OnboardingPassResponse,
} from './types';
