#!/usr/bin/env node
// deploy/cn/render-overlay.mjs — writes the kustomize overlay that turns the
// deploy/cn/k8s base into a deployable release (WP-76). Used by
// .github/workflows/deploy-cn.yml and by ops for a manual deploy.
//
//   node deploy/cn/render-overlay.mjs \
//     --registry registry.cn-shanghai.aliyuncs.com --namespace goapply \
//     --tag <git sha> --slb-cert-id <SLB certificate id> \
//     [--worker-replicas 0] --out deploy/cn/overlays/prod
//
// The overlay only sets image names/tags, the worker replica count and the
// HTTPS listener (certificate id + 80 → 443 redirect) on the gateway SLB. It
// holds no secret: a certificate id is an identifier, not key material.
// `deploy/cn/overlays/` is output; do not commit it.

import { mkdirSync, writeFileSync } from 'node:fs';
import { join, relative, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

export const COMPONENTS = ['web', 'api', 'worker', 'gateway'];
const BASE_DIR = resolve(fileURLToPath(new URL('./k8s', import.meta.url)));

const REGISTRY_RE = /^[a-z0-9.-]+(:[0-9]+)?$/;
const NAMESPACE_RE = /^[a-z0-9]+([._-][a-z0-9]+)*$/;
const TAG_RE = /^[A-Za-z0-9_][A-Za-z0-9_.-]{0,127}$/;
const CERT_RE = /^[A-Za-z0-9_-]{1,128}$/;

const ANNOTATION = 'service.beta.kubernetes.io~1alibaba-cloud-loadbalancer';

/** Validate options; returns a list of problems (empty when usable). */
export function overlayProblems(o) {
  const problems = [];
  if (!o.registry || !REGISTRY_RE.test(o.registry)) problems.push('--registry must be a registry host (e.g. registry.cn-shanghai.aliyuncs.com)');
  if (!o.namespace || !NAMESPACE_RE.test(o.namespace)) problems.push('--namespace must be an ACR namespace');
  if (!o.tag || !TAG_RE.test(o.tag)) problems.push('--tag must be an image tag (the git sha)');
  if (!o.slbCertId || !CERT_RE.test(o.slbCertId)) {
    problems.push('--slb-cert-id is required: the SLB certificate id for the ICP-filed domain (HTTPS terminates at the SLB)');
  }
  const replicas = Number(o.workerReplicas ?? 0);
  if (!Number.isInteger(replicas) || replicas < 0 || replicas > 20) problems.push('--worker-replicas must be an integer 0-20');
  return problems;
}

/** The overlay's kustomization.yaml text. `baseRel` is the path from the overlay to deploy/cn/k8s. */
export function renderOverlay(o, baseRel = '../../k8s') {
  const problems = overlayProblems(o);
  if (problems.length) throw new Error(`Cannot render the CN overlay:\n  - ${problems.join('\n  - ')}`);
  const replicas = Number(o.workerReplicas ?? 0);
  const lines = [
    '# GENERATED by deploy/cn/render-overlay.mjs — do not commit.',
    'apiVersion: kustomize.config.k8s.io/v1beta1',
    'kind: Kustomization',
    'resources:',
    `  - ${baseRel}`,
    'images:',
    ...COMPONENTS.flatMap((c) => [
      `  - name: goapply-${c}`,
      `    newName: ${o.registry}/${o.namespace}/goapply-${c}`,
      `    newTag: "${o.tag}"`,
    ]),
    'replicas:',
    '  - name: worker',
    `    count: ${replicas}`,
    'patches:',
    '  - target:',
    '      kind: Service',
    '      name: gateway',
    '    patch: |-',
    '      - op: add',
    '        path: /spec/ports/-',
    '        value: { name: https, port: 443, targetPort: http, protocol: TCP }',
    '      - op: replace',
    `        path: /metadata/annotations/${ANNOTATION}-protocol-port`,
    '        value: "https:443,http:80"',
    '      - op: add',
    `        path: /metadata/annotations/${ANNOTATION}-cert-id`,
    `        value: "${o.slbCertId}"`,
    '      - op: add',
    `        path: /metadata/annotations/${ANNOTATION}-forward-port`,
    '        value: "80:443"',
  ];
  return `${lines.join('\n')}\n`;
}

function parseArgs(argv) {
  const map = { '--registry': 'registry', '--namespace': 'namespace', '--tag': 'tag', '--slb-cert-id': 'slbCertId', '--worker-replicas': 'workerReplicas', '--out': 'out' };
  const o = {};
  for (let i = 0; i < argv.length; i += 1) {
    const key = map[argv[i]];
    if (!key) throw new Error(`Unknown argument: ${argv[i]}`);
    o[key] = argv[++i];
  }
  return o;
}

export function main(argv = process.argv.slice(2), io = { log: console.log, error: console.error }) {
  let o;
  try {
    o = parseArgs(argv);
    if (!o.out) throw new Error('--out <directory> is required');
    const out = resolve(o.out);
    const text = renderOverlay(o, relative(out, BASE_DIR).split('\\').join('/'));
    mkdirSync(out, { recursive: true });
    writeFileSync(join(out, 'kustomization.yaml'), text);
    io.log(`Wrote ${join(o.out, 'kustomization.yaml')}`);
    return 0;
  } catch (err) {
    io.error(err.message);
    return 2;
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  process.exitCode = main();
}
